import type { AppSnapshot, Client, Deal, Meeting, Task } from '../domain/models.ts';
import type { ConnectInput, CrmResult, SyncProgress } from '../domain/crm.ts';
import type {KonturConnectInput,KonturResult,KonturProgress,MeetingArtifacts,TranscriptPage,TalkImport} from '../domain/kontur.ts';
export interface KonturDesktopApi {openKontur(domain:string):Promise<KonturResult>;connectKontur(input:KonturConnectInput):Promise<KonturResult>;syncKontur():Promise<KonturResult>;disconnectKontur(purge:boolean):Promise<KonturResult>;getMeetingArtifacts(id:string):Promise<MeetingArtifacts>;getTranscriptPage(id:string,offset:number,limit:number,search:string):Promise<TranscriptPage>;openTalkRecording(id:string,recordingId:string):Promise<KonturResult>;onKonturProgress(listener:(progress:KonturProgress)=>void):()=>void}

export interface AmoCrmAdapter { readonly kind: 'amoCRM'; fetchClients(): Promise<Client[]>; fetchDeals(): Promise<Deal[]> }
export interface KonturTalkAdapter { identify():Promise<{externalUserId:string|null;displayName:string|null}>;fetchMeetings(start:string,end:string,progress?:(done:number,total:number)=>void):Promise<TalkImport[]> }
export interface AiProvider { readonly kind: 'AI'; summarize(meeting: Meeting): Promise<string> }
export interface SecureCredentialStore { set(key: string, secret: string): Promise<void>; get(key: string): Promise<string | null>; delete(key: string): Promise<void> }
export interface AppRepository { initialize(): Promise<void>; snapshot(): Promise<AppSnapshot>; setTaskCompleted(id: string, completed: boolean): Promise<void>; updateProfile(displayName: string): Promise<void>; setSetting(key: string, value: string): Promise<void>; resetDemo(): Promise<void> }
export interface DesktopApi extends KonturDesktopApi { findMeetingClients(id?:string):Promise<AppSnapshot>; confirmMeetingClient(id:string,selection:import('../domain/matching.ts').MatchSelection):Promise<AppSnapshot>; unlinkMeetingClient(id:string):Promise<AppSnapshot>; getTranscriptLocation(id:string,segmentId:string):Promise<number>; getSnapshot(): Promise<AppSnapshot>; setTaskCompleted(id: string, completed: boolean): Promise<AppSnapshot>; updateProfile(displayName: string): Promise<AppSnapshot>; setSetting(key: string, value: string): Promise<AppSnapshot>; resetDemo(): Promise<AppSnapshot>; setWindowTheme?(dark: boolean): Promise<void>; connectCrm(input: ConnectInput): Promise<CrmResult>; openCrmBrowser(domain:string):Promise<CrmResult>; verifyCrmBrowser():Promise<CrmResult>; syncCrm(): Promise<CrmResult>; disconnectCrm(purge: boolean): Promise<CrmResult>; writeCrm(command: import('../domain/crmWrite.ts').CrmCommand): Promise<import('../domain/crmWrite.ts').CrmWriteResult>; refreshWorkspace(clientId: string): Promise<CrmResult>; getTimeline(clientId: string): Promise<import('../domain/crmWrite.ts').TimelineData>; openInAmo?(kind: 'lead'|'contact', id: number): Promise<CrmResult>; onSyncProgress(listener: (progress: SyncProgress) => void): () => void }
export type TaskMutation = Pick<Task, 'id' | 'completed'>;
