// @vitest-environment node
import { describe, expect, it, vi } from 'vitest';
import { normalizeDomain, endpoint, CrmError } from '../electron/amocrm/security.ts';
import { Transport } from '../electron/amocrm/transport.ts';
import { OAuthSession, validateConnect, type CredentialBundle } from '../electron/amocrm/oauth.ts';
import { AmoClient } from '../electron/amocrm/client.ts';
import { collectSync } from '../electron/amocrm/sync.ts';
import { mapWorkspace, phoneOrEmail } from '../electron/amocrm/mapping.ts';
import type { SecureCredentialStore } from '../src/services/contracts.ts';
import type { CrmAccount, CrmCache, CrmRecord } from '../src/domain/crm.ts';
const bundle:CredentialBundle={domain:'test.amocrm.ru',clientId:'client',clientSecret:'SECRET_TEST',redirectUri:'https://example.com/callback',accessToken:'ACCESS_OLD',refreshToken:'REFRESH_OLD',expiresAt:Date.now()+86400000};
const account:CrmAccount={id:'1_test',externalId:1,domain:bundle.domain,name:'Test',currentUserId:9,authorized:true,expiresAt:bundle.expiresAt,lastSyncAt:null,state:'idle',error:null};
const memoryStore=():SecureCredentialStore=>({set:vi.fn(async()=>{}),get:vi.fn(async()=>null),delete:vi.fn(async()=>{})});
const response=(data:unknown,status=200,headers?:Record<string,string>)=>new Response(status===204?null:JSON.stringify(data),{status,headers});
const clientFor=(fetcher:typeof fetch,store=memoryStore(),b=bundle)=>{const transport=new Transport(fetcher,async()=>{});return new AmoClient(b.domain,new OAuthSession({...b},store,account.id,transport),transport);};
const list=(kind:string,items:unknown[],next?:string)=>({_embedded:{[kind]:items},_links:next?{next:{href:next}}:{}});
describe('amoCRM security and transport',()=>{
  it('normalizes a subdomain and HTTPS URL',()=>{expect(normalizeDomain('test')).toBe('test.amocrm.ru');expect(normalizeDomain('https://TEST.amocrm.ru/')).toBe('test.amocrm.ru');});
  it.each(['http://test.amocrm.ru','evil.com','test.amocrm.ru.evil.com','test.amocrm.ru:4431','https://user@test.amocrm.ru','test.amocrm.ru/path','127.0.0.1','test.amocrm.ru?x=1'])('rejects unsafe domain %s',value=>expect(()=>normalizeDomain(value)).toThrow());
  it('rejects arbitrary endpoint and mutations',async()=>{expect(()=>endpoint(bundle.domain,'https://evil.com/api/v4/leads')).toThrow();expect(()=>endpoint(bundle.domain,'/api/v4/users')).toThrow();const transport=new Transport(vi.fn(),async()=>{});await expect(transport.request(new URL('https://test.amocrm.ru/api/v4/leads'),undefined,{grant_type:'refresh_token'})).rejects.toThrow();});
  it('validates complete wizard inputs',()=>{expect(()=>validateConnect({domain:'test',clientId:'x'})).toThrow();expect(()=>validateConnect({domain:'test',clientId:'x',clientSecret:'s',code:'c',redirectUri:'file:///secret'})).toThrow();});
  it('retries 429 and 5xx with bounded delays and safe logs',async()=>{const delays:number[]=[];const logs:string[]=[];const mock=vi.fn().mockResolvedValueOnce(response({},429,{'Retry-After':'2'})).mockResolvedValueOnce(response({},503)).mockResolvedValueOnce(response({id:1}));const transport=new Transport(mock,async ms=>{delays.push(ms);},Date.now,line=>logs.push(line));expect(await transport.request(new URL('https://test.amocrm.ru/api/v4/account'),'SECRET_TOKEN')).toEqual({id:1});expect(mock).toHaveBeenCalledTimes(3);expect(delays).toContain(2000);expect(logs.join('')).not.toContain('SECRET_TOKEN');expect(logs[0]).toContain('request=');});
  it('does not retry a rotating OAuth POST',async()=>{const mock=vi.fn(async()=>response({},503));const transport=new Transport(mock,async()=>{});await expect(transport.request(new URL('https://test.amocrm.ru/oauth2/access_token'),undefined,{grant_type:'refresh_token'})).rejects.toThrow();expect(mock).toHaveBeenCalledTimes(1);});
  it.each([401,402,403,404,422])('returns controlled error for HTTP %i',async status=>{const client=clientFor(vi.fn(async()=>response({secret:'DO_NOT_SHOW'},status)));await expect(client.get('/api/v4/account')).rejects.toBeInstanceOf(CrmError);});
  it('hides raw network errors',async()=>{const client=clientFor(vi.fn(async()=>{throw new Error('secret=DO_NOT_SHOW');}));await expect(client.get('/api/v4/account')).rejects.toThrow('Проверьте интернет');});
  it('serializes concurrent requests at 5 requests per second',async()=>{let time=0;const starts:number[]=[];const transport=new Transport(vi.fn(async()=>{starts.push(time);return response({});}),async ms=>{time+=ms;},()=>time);await Promise.all(Array.from({length:5},()=>transport.request(new URL('https://test.amocrm.ru/api/v4/account'))));expect(starts).toEqual([0,200,400,600,800]);});
});
describe('OAuth rotation',()=>{
  it('single-flights concurrent expiry and saves the pair before release',async()=>{let persisted=false;const store=memoryStore();store.set=vi.fn(async(_key,value)=>{const parsed=JSON.parse(value);expect(parsed.accessToken).toBe('NEW_ACCESS');expect(parsed.refreshToken).toBe('NEW_REFRESH');await Promise.resolve();persisted=true;});const mock=vi.fn(async()=>response({access_token:'NEW_ACCESS',refresh_token:'NEW_REFRESH',expires_in:86400}));const session=new OAuthSession({...bundle,expiresAt:0},store,account.id,new Transport(mock,async()=>{}));const values=await Promise.all(Array.from({length:20},()=>session.token().then(t=>{expect(persisted).toBe(true);return t;})));expect(new Set(values)).toEqual(new Set(['NEW_ACCESS']));expect(mock).toHaveBeenCalledTimes(1);});
  it('concurrent 401s refresh once and late rejection uses rotated token',async()=>{const mock=vi.fn(async(_url,options)=>options?.method==='POST'?response({access_token:'NEW_ACCESS',refresh_token:'NEW_REFRESH',expires_in:86400}):(options?.headers as Record<string,string>).Authorization==='Bearer ACCESS_OLD'?response({},401):response({id:1}));const client=clientFor(mock);expect(await Promise.all(Array.from({length:8},()=>client.get('/api/v4/account')))).toHaveLength(8);expect(mock.mock.calls.filter(c=>c[1]?.method==='POST')).toHaveLength(1);});
  it('blocks reuse of a consumed refresh after persistence failure',async()=>{const store=memoryStore();store.set=vi.fn(async()=>{throw new Error('disk');});const mock=vi.fn(async()=>response({access_token:'NEW',refresh_token:'ROTATED',expires_in:10}));const session=new OAuthSession({...bundle,expiresAt:0},store,account.id,new Transport(mock,async()=>{}));await expect(session.token()).rejects.toThrow();await expect(session.token()).rejects.toThrow('Подключите amoCRM заново');expect(mock).toHaveBeenCalledTimes(1);});
});
describe('pagination and mapping',()=>{
  it('reads all pages with filters and handles empty 204',async()=>{const calls:string[]=[];const client=clientFor(vi.fn(async input=>{const url=new URL(String(input));calls.push(url.search);return url.searchParams.get('page')==='1'?response(list('leads',[{id:1}],'/api/v4/leads?page=2')):response(list('leads',[{id:2}]));}));expect(await client.all('/api/v4/leads','leads',{'filter[responsible_user_id][0]':'9'})).toHaveLength(2);expect(calls[1]).toContain('responsible_user_id');expect(await clientFor(vi.fn(async()=>response(null,204))).all('/api/v4/leads','leads')).toEqual([]);});
  it.each(['https://evil.com/api/v4/leads?page=2','/api/v4/leads?page=1','/api/v4/tasks?page=2'])('rejects invalid next link %s',async next=>{const client=clientFor(vi.fn(async()=>response(list('leads',[{id:1}],next))));await expect(client.all('/api/v4/leads','leads')).rejects.toThrow();});
  it('fails repeated pages instead of truncating',async()=>{const client=clientFor(vi.fn(async input=>{const p=Number(new URL(String(input)).searchParams.get('page'));return response(list('leads',[{id:1}],`/api/v4/leads?page=${p+1}`));}));await expect(client.all('/api/v4/leads','leads')).rejects.toThrow('повторила страницу');});
  it('maps separate company and contact identities and custom phone/email',()=>{const contact:CrmRecord={id:20,name:'Ирина',custom_fields_values:[{field_id:1,field_code:'PHONE',values:[{value:'+7999'}]},{field_code:'EMAIL',values:[{value:'i@example.com'}]}]};const cache:CrmCache={account,contacts:[contact],companies:[{id:30,name:'Компания'}],pipelines:[{id:5,name:'Продажи',_embedded:{statuses:[{id:50,name:'Переговоры'}]}}],notes:[],fields:[]};const leads=[{id:10,name:'Сделка',responsible_user_id:9,pipeline_id:5,status_id:50,price:123,updated_at:1234}];const data=mapWorkspace(account,leads,cache,[{leadId:10,entityType:'contacts',entityId:20,primary:true},{leadId:10,entityType:'companies',entityId:30,primary:false}],[]);expect(data.clients[0].id).toContain('company:30');expect(data.clients[0].name).toBe('Ирина');expect(data.clients[0].phone).toBe('+7999');expect(data.deals[0].pipelineName).toBe('Продажи');expect(phoneOrEmail(contact,'EMAIL')).toBe('i@example.com');});
  it('does not fabricate a missing contact and marks closed deals',()=>{const cache:CrmCache={account,contacts:[],companies:[],pipelines:[],notes:[],fields:[]};const data=mapWorkspace(account,[{id:10,name:'Без контакта',responsible_user_id:9,status_id:142}],cache,[],[]);expect(data.clients[0].externalId).toBeNull();expect(data.clients[0].id).toContain('workspace:10');expect(data.deals[0].stageName).toBe('Успешно реализовано');});
  it('rejects leads outside the current user scope',()=>{expect(()=>mapWorkspace(account,[{id:10,responsible_user_id:8}],{account,contacts:[],companies:[],pipelines:[],notes:[],fields:[]},[],[])).toThrow('другого ответственного');});
});
describe('sync collector',()=>{
  it('resolves official link main_contact and company without conflating equal IDs',async()=>{const client=clientFor(vi.fn(async input=>{const u=new URL(String(input));if(u.pathname.endsWith('/account'))return response({id:1,current_user_id:9});if(u.pathname.endsWith('/pipelines'))return response(list('pipelines',[]));if(u.pathname==='/api/v4/leads')return response(list('leads',[{id:10,responsible_user_id:9}]));if(u.pathname.endsWith('/links'))return response(list('links',[{to_entity_type:'contacts',to_entity_id:20,metadata:{main_contact:true}},{to_entity_type:'companies',to_entity_id:20,metadata:null}]));const kind=u.pathname.split('/')[3];if(kind==='contacts'||kind==='companies')return response(list(kind,[{id:20,name:kind}]));if(kind==='tasks')return response(list('tasks',[]));if(u.pathname.endsWith('/notes'))return response(list('notes',[]));if(u.pathname.endsWith('/custom_fields'))return response(list('custom_fields',[]));return response({},403);}));const batch=await collectSync(client,account,()=>{});expect(batch.relations).toHaveLength(2);expect(batch.relations.find(r=>r.entityType==='contacts')?.primary).toBe(true);expect(batch.contacts[0].name).toBe('contacts');expect(batch.companies[0].name).toBe('companies');});
  it('falls back from unsupported lead filter, uses account user, retains optional failure',async()=>{const paths:string[]=[];const client=clientFor(vi.fn(async input=>{const u=new URL(String(input));paths.push(u.pathname);if(u.pathname.endsWith('/account'))return response({id:1,current_user_id:9,name:'Account'});if(u.pathname.endsWith('/pipelines'))return response(list('pipelines',[]));if(u.pathname==='/api/v4/leads'){if(u.search.includes('responsible_user_id'))return response({},422);return response(list('leads',[{id:10,responsible_user_id:9,_embedded:{contacts:[],companies:[]}},{id:11,responsible_user_id:7}]));}if(u.pathname.endsWith('/tasks'))return response({},403);if(u.pathname.endsWith('/notes'))return response(list('notes',[{id:100,params:{text:'Примечание'}}]));if(u.pathname.endsWith('/custom_fields'))return response(list('custom_fields',[{id:200,name:'Поле',type:'text'}]));if(u.pathname.endsWith('/custom_fields/groups'))return response(list('custom_field_groups',[]));throw new Error('unexpected');}));const batch=await collectSync(client,account,()=>{});expect(batch.leads.map(l=>l.id)).toEqual([10]);expect(batch.tasks).toBeUndefined();expect(batch.notes?.[0].entity_id).toBe(10);expect(batch.fields).toHaveLength(3);expect(batch.warnings).toHaveLength(1);expect(paths.some(p=>p.includes('users'))).toBe(false);});
});
