// @vitest-environment node
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import initSqlJs from 'sql.js';
import { seedDemo } from '../electron/seed.ts';
import { SqliteRepository } from '../electron/repository.ts';
import { EncryptedFileStore } from '../electron/encryptedStore.ts';
import { CrmService } from '../electron/amocrm/service.ts';
import { Transport } from '../electron/amocrm/transport.ts';
import { accountFixture, batchFixture } from './crmFixture.ts';
import type { SecureCredentialStore } from '../src/services/contracts.ts';
import type { BrowserAccess } from '../electron/amocrm/browserAccess.ts';
import { AmoClient } from '../electron/amocrm/client.ts';
let directory:string;let repo:SqliteRepository;const root=process.cwd();const make=(migration=path.join(root,'migrations'))=>new SqliteRepository(path.join(directory,'test.sqlite'),migration,root);
beforeEach(async()=>{directory=fs.mkdtempSync(path.join(os.tmpdir(),'talkcrm-crm-'));repo=make();await repo.initialize();});
afterEach(()=>{repo.close();fs.rmSync(directory,{recursive:true,force:true});});
const commit=async()=>{await repo.connectAccount(accountFixture);await repo.commitCrmSync(batchFixture(),await repo.startSync());};
describe('migration and CRM cache',()=>{
  it('validates employee identity before persisting a browser connection, never writing cookies to SQLite',async()=>{
    const secrets=new Map<string,string>();const store:SecureCredentialStore={get:async k=>secrets.get(k)??null,set:async(k,v)=>{secrets.set(k,v);},delete:async k=>{secrets.delete(k);}};
    const client=new AmoClient('test.amocrm.ru',null,new Transport(async()=>new Response(JSON.stringify({id:1,current_user_id:9})),async()=>{}));
    const browser:BrowserAccess={open:vi.fn(async()=>{}),client:vi.fn(async()=>client),persist:vi.fn(async()=>{await store.set('amocrm:1_test:browser','COOKIE_SENTINEL');}),clear:vi.fn(async()=>{}),close:vi.fn()};
    const service=new CrmService(repo,store,new Transport(vi.fn()),()=>{},browser);expect((await service.openBrowser('test')).ok).toBe(true);expect(repo.getCrmAccount()).toBeNull();expect((await service.verifyBrowser()).ok).toBe(true);expect(repo.getCrmAccount()?.authMode).toBe('browser');expect(repo.getCrmAccount()?.currentUserId).toBe(9);expect(secrets.get('amocrm:1_test:browser')).toBe('COOKIE_SENTINEL');expect(fs.readFileSync(path.join(directory,'test.sqlite')).toString()).not.toContain('COOKIE_SENTINEL');expect(JSON.stringify(await repo.snapshot())).not.toContain('COOKIE_SENTINEL');repo.close();repo=make();await repo.initialize();expect(repo.getCrmAccount()?.authMode).toBe('browser');await new CrmService(repo,store,new Transport(vi.fn()),()=>{},browser).disconnect(false);expect(secrets.size).toBe(0);expect(browser.clear).toHaveBeenCalledOnce();
  });
  it('preserves the connected cache when browser authorization fails',async()=>{
    await commit();const before=await repo.snapshot();const store:SecureCredentialStore={get:async()=>null,set:vi.fn(),delete:vi.fn()};const browser:BrowserAccess={open:async()=>{},client:async()=>new AmoClient('test.amocrm.ru',null,new Transport(async()=>new Response('{}',{status:401}),async()=>{})),persist:vi.fn(),clear:async()=>{},close:()=>{}};const service=new CrmService(repo,store,new Transport(vi.fn()),()=>{},browser);await service.openBrowser('test');expect((await service.verifyBrowser()).ok).toBe(false);expect(browser.persist).not.toHaveBeenCalled();expect((await repo.snapshot()).deals).toEqual(before.deals);expect(repo.getCrmAccount()?.authMode).toBe('oauth');
  });
  it('migrates existing Phase 2 OAuth accounts to browser-capable schema',async()=>{
    repo.close();fs.unlinkSync(path.join(directory,'test.sqlite'));const oldMigrations=path.join(directory,'phase2');fs.mkdirSync(oldMigrations);for(const name of ['001_initial.sql','002_amocrm.sql'])fs.copyFileSync(path.join(root,'migrations',name),path.join(oldMigrations,name));repo=make(oldMigrations);await repo.initialize();repo.close();const SQL=await initSqlJs();const oldDb=new SQL.Database(new Uint8Array(fs.readFileSync(path.join(directory,'test.sqlite'))));const a=accountFixture;oldDb.run('INSERT INTO crm_accounts VALUES(?,?,?,?,?,?,?,?,?,?,?)',[a.id,a.externalId,a.domain,a.name,a.currentUserId,1,a.expiresAt,a.lastSyncAt,a.state,a.error,a.currency??null]);oldDb.run("INSERT INTO app_settings(key,value) VALUES('active_crm_account',?)",[a.id]);fs.writeFileSync(path.join(directory,'test.sqlite'),Buffer.from(oldDb.export()));oldDb.close();repo=make();await repo.initialize();expect(repo.getCrmAccount()?.authMode).toBe('oauth');expect(repo.getCrmAccount()?.currentUserId).toBe(accountFixture.currentUserId);
  });
  it('exchanges code, stores secrets exclusively in the secure store and removes them on disconnect',async()=>{let secret:string|null=null;const calls:{path:string;method:string}[]=[];const store:SecureCredentialStore={get:async()=>secret,set:async(_key,value)=>{secret=value;},delete:async(key)=>{if(key.endsWith(':oauth'))secret=null;}};const transport=new Transport(vi.fn(async(input,options)=>{const url=new URL(String(input));calls.push({path:url.pathname,method:options?.method??'GET'});return new Response(JSON.stringify(url.pathname==='/oauth2/access_token'?{access_token:'ACCESS_SENTINEL',refresh_token:'REFRESH_SENTINEL',expires_in:86400}:{id:1,current_user_id:9,name:'Test'}));}),async()=>{});const service=new CrmService(repo,store,transport,()=>{});const input={domain:'test',clientId:'client',clientSecret:'SECRET_SENTINEL',redirectUri:'https://example.com',code:'CODE_SENTINEL'};expect((await service.connect(input)).ok).toBe(true);expect(input.code).toBe('');expect(input.clientSecret).toBe('');expect(secret).toContain('ACCESS_SENTINEL');expect(secret).not.toContain('CODE_SENTINEL');const raw=fs.readFileSync(path.join(directory,'test.sqlite')).toString();for(const value of ['ACCESS_SENTINEL','REFRESH_SENTINEL','SECRET_SENTINEL','CODE_SENTINEL'])expect(raw).not.toContain(value);expect(calls).toEqual([{path:'/oauth2/access_token',method:'POST'},{path:'/api/v4/account',method:'GET'}]);await service.disconnect(false);expect(secret).toBeNull();});
  it('migrates a Phase 1 database while preserving settings and task changes',async()=>{repo.close();fs.unlinkSync(path.join(directory,'test.sqlite'));const oldMigrations=path.join(directory,'phase1');fs.mkdirSync(oldMigrations);fs.copyFileSync(path.join(root,'migrations','001_initial.sql'),path.join(oldMigrations,'001_initial.sql'));const SQL=await initSqlJs();const db=new SQL.Database();db.run(fs.readFileSync(path.join(oldMigrations,'001_initial.sql'),'utf8'));db.run("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);INSERT INTO schema_migrations VALUES(1,'001_initial.sql','2026-10-01')");seedDemo(db);db.run("UPDATE users SET display_name='Сохранённый профиль';UPDATE app_settings SET value='off' WHERE key='notifications';UPDATE tasks SET completed=1 WHERE id='t1'");fs.writeFileSync(path.join(directory,'test.sqlite'),Buffer.from(db.export()));db.close();repo=make();await repo.initialize();const data=await repo.snapshot();expect(data.profile.displayName).toBe('Сохранённый профиль');expect(data.settings.notifications).toBe('off');expect(data.tasks.find(t=>t.id==='t1')?.completed).toBe(true);expect(data.settings.data_mode).toBe('demo');await commit();expect((await repo.snapshot()).deals).toHaveLength(2);});
  it('upserts a second sync, separates demo and CRM, and restores offline',async()=>{await commit();await commit();const data=await repo.snapshot();expect(data.deals).toHaveLength(2);expect(data.clients).toHaveLength(2);expect(data.meetings).toHaveLength(0);expect(data.crm?.contacts).toHaveLength(1);repo.close();repo=make();await repo.initialize();expect((await repo.snapshot()).deals).toEqual(data.deals);await repo.setSetting('data_mode','demo');expect((await repo.snapshot()).deals).toHaveLength(10);expect((await repo.snapshot()).meetings).toHaveLength(8);});
  it('rejects CRM task changes and preserves cache on demo reset',async()=>{await commit();const id=(await repo.snapshot()).tasks[0].id;await expect(repo.setTaskCompleted(id,true)).rejects.toThrow('read-only');await repo.updateProfile('Профиль');await repo.resetDemo();const data=await repo.snapshot();expect(data.tasks[0].completed).toBe(false);expect(data.crm?.notes).toHaveLength(1);expect(data.profile.displayName).toBe('Профиль');});
  it('retains optional cache when a category fails',async()=>{await commit();const batch=batchFixture();delete batch.tasks;delete batch.notes;delete batch.fields;batch.warnings.push('Нет доступа к задачам');await repo.commitCrmSync(batch,await repo.startSync());const data=await repo.snapshot();expect(data.tasks).toHaveLength(1);expect(data.crm?.notes).toHaveLength(1);expect(data.crm?.fields).toHaveLength(1);expect(data.crm?.account?.state).toBe('partial_error');});
  it('rolls back a broken core transaction without replacing usable data',async()=>{await commit();const batch=batchFixture();batch.relations.push({...batch.relations[0]});await expect(repo.commitCrmSync(batch,await repo.startSync())).rejects.toThrow();expect((await repo.snapshot()).deals).toHaveLength(2);expect((await repo.snapshot()).crm?.notes).toHaveLength(1);});
  it('marks missing entities unavailable without deleting them',async()=>{await commit();const batch=batchFixture();batch.leads=[];batch.contacts=[];batch.companies=[];batch.relations=[];await repo.commitCrmSync(batch,await repo.startSync());const data=await repo.snapshot();expect(data.deals).toHaveLength(2);expect(data.deals.every(d=>d.availability==='unavailable')).toBe(true);expect(data.crm?.contacts).toHaveLength(1);});
  it('disconnects with cache retention and explicitly purges only the account',async()=>{await commit();await repo.disconnectAccount(false);let data=await repo.snapshot();expect(data.crm?.account?.authorized).toBe(false);expect(data.deals).toHaveLength(2);await repo.disconnectAccount(true);data=await repo.snapshot();expect(data.crm?.account).toBeNull();expect(data.settings.data_mode).toBe('demo');expect(data.deals).toHaveLength(10);});
  it('records core failure without modifying prior data',async()=>{await commit();const fetcher=vi.fn(async()=>new Response('{}',{status:503}));const store:SecureCredentialStore={get:async()=>JSON.stringify({domain:accountFixture.domain,clientId:'id',clientSecret:'SECRET_SENTINEL',redirectUri:'https://example.com',accessToken:'ACCESS_SENTINEL',refreshToken:'REFRESH_SENTINEL',expiresAt:Date.now()+86400000}),set:async()=>{},delete:async()=>{}};const service=new CrmService(repo,store,new Transport(fetcher,async()=>{}),()=>{});const result=await service.sync();expect(result.ok).toBe(false);const data=await repo.snapshot();expect(data.deals).toHaveLength(2);expect(data.crm?.account?.state).toBe('failed');const raw=fs.readFileSync(path.join(directory,'test.sqlite')).toString();expect(raw).not.toContain('SECRET_SENTINEL');expect(raw).not.toContain('ACCESS_SENTINEL');expect(JSON.stringify(data)).not.toContain('REFRESH_SENTINEL');});
  it('deduplicates concurrent manual sync and handles missing secrets',async()=>{await repo.connectAccount(accountFixture);const store:SecureCredentialStore={get:async()=>null,set:async()=>{},delete:async()=>{}};const progress=vi.fn();const service=new CrmService(repo,store,new Transport(vi.fn(),async()=>{}),progress);const results=await Promise.all([service.sync(),service.sync(),service.sync()]);expect(results.every(r=>!r.ok)).toBe(true);expect(progress).toHaveBeenCalledTimes(1);expect(repo.getCrmAccount()?.authorized).toBe(false);});
});
describe('encrypted atomic credential bundles',()=>{
  it('namespaces accounts and never writes plaintext with an injected cipher',async()=>{const cipher={available:()=>true,encrypt:(s:string)=>Buffer.from(Buffer.from(s).map(v=>v^91)),decrypt:(b:Buffer)=>Buffer.from(b.map(v=>v^91)).toString()};const store=new EncryptedFileStore(path.join(directory,'credentials'),cipher);await store.set('amocrm:1_test:oauth','SECRET_SENTINEL');await store.set('amocrm:2_test:oauth','OTHER');expect(await store.get('amocrm:1_test:oauth')).toBe('SECRET_SENTINEL');expect(await store.get('amocrm:2_test:oauth')).toBe('OTHER');const files=fs.readdirSync(path.join(directory,'credentials'));expect(files).toHaveLength(2);expect(files.every(file=>!fs.readFileSync(path.join(directory,'credentials',file)).toString().includes('SECRET_SENTINEL'))).toBe(true);await store.delete('amocrm:1_test:oauth');expect(await store.get('amocrm:1_test:oauth')).toBeNull();});
  it('fails closed without OS encryption and rejects traversal',async()=>{const store=new EncryptedFileStore(directory,{available:()=>false,encrypt:()=>Buffer.from(''),decrypt:()=>''});await expect(store.set('amocrm:1_test:oauth','SECRET')).rejects.toThrow('OS encryption');await expect(store.get('../../x')).rejects.toThrow('namespace');});
  it('keeps the previously committed pair when encryption fails',async()=>{let fail=false;const store=new EncryptedFileStore(directory,{available:()=>true,encrypt:s=>{if(fail)throw new Error('cipher');return Buffer.from(s);},decrypt:b=>b.toString()});await store.set('amocrm:1_test:oauth','OLD_PAIR');fail=true;await expect(store.set('amocrm:1_test:oauth','NEW_PAIR')).rejects.toThrow();expect(await store.get('amocrm:1_test:oauth')).toBe('OLD_PAIR');expect(fs.readdirSync(directory).filter(f=>f.endsWith('.tmp'))).toHaveLength(0);});
});


