// @vitest-environment node
import {expect,it} from 'vitest';
import {normalizeRecording,readiness} from '../electron/kontur/mapping.ts';
import {allowedTalkLogin,normalizeTalkDomain,sourceRecordingUrl} from '../electron/kontur/security.ts';
it('keeps exact chunk speaker, precision, order and separates conference from recording',()=>{
  const m=normalizeRecording({id:'record1',conferenceKey:'conference1',title:'Тест',createdDate:'2026-10-03T13:00:00Z',status:'complete'},{transcriptionV2:{status:'success',transcriptId:'transcript1',tracks:[{speaker:{anonymousName:'Клиент'},chunks:[{chunkId:'a',text:'Первое',startTimeOffsetInMillis:42123,endTimeOffsetInMillis:42876,diarizedSpeaker:{userInfo:{key:'u1',firstname:'Дмитрий'}}}]}]},protocolV2:{status:'success',summaryId:'protocol1',chunks:[{type:'tasks',text:'Исходная задача',timestamp:42,version:2}]}},'test.ktalk.ru');
  expect(m.meetingExternalId).toBe('conference1');expect(m.recordingExternalId).toBe('record1');expect(m.startedAt).toBeNull();expect(m.segments[0].speakerName).toBe('Дмитрий');expect(m.segments[0].startMs).toBe(42123);expect(m.segments[0].endMs).toBe(42876);expect(m.artifacts[3].sections[0].type).toBe('tasks');expect(m.artifacts[3].sections[0].timestampMs).toBe(42000);
});
it('does not import source-hidden summaries or chunks',()=>{const m=normalizeRecording({id:'r1'},{shortSummaryV2:{status:'success',hidden:true,chunks:[{text:'Скрыто'}]},protocolV2:{status:'success',chunks:[{text:'Доступно'},{text:'Скрыто',hiddenStatus:{isHidden:true}}]}},'test.ktalk.ru');expect(m.artifacts[2].text).toBeNull();expect(m.artifacts[3].text).toBe('Доступно');});
it('fails closed on unknown statuses and invalid DTOs',()=>{expect(()=>readiness('newStatus')).toThrow();expect(()=>normalizeRecording({id:'r1'},{transcriptionV2:{status:'success',tracks:[{chunks:[{text:42}]}]}},'test.ktalk.ru')).toThrow();});
it('allows the authorized Yandex flow and blocks unrelated hosts, schemes and source links',()=>{expect(allowedTalkLogin('https://oauth.yandex.ru/authorize','test.ktalk.ru')).toBe(true);expect(allowedTalkLogin('https://oauth.yandex.ru.evil.example/','test.ktalk.ru')).toBe(false);expect(allowedTalkLogin('http://test.ktalk.ru/','test.ktalk.ru')).toBe(false);expect(()=>normalizeTalkDomain('https://test.ktalk.ru@evil.example')).toThrow();expect(sourceRecordingUrl('https://evil.example/recordings/r1','test.ktalk.ru')).toBeNull();expect(sourceRecordingUrl('/recordings/r1','test.ktalk.ru')).toBe('https://test.ktalk.ru/recordings/r1');});
