import { randomUUID } from 'node:crypto';
import type { Database, SqlValue } from 'sql.js';
import type { CrmAccount, CrmCache, CrmRecord, CrmRelation, CrmTalk, SyncBatch, SyncState } from '../src/domain/crm.ts';
import { localId, mapWorkspace, projectRecord } from './amocrm/mapping.ts';
type Row=Record<string,SqlValue>;
export function query(db:Database,sql:string,params:SqlValue[]=[]):Row[]{const s=db.prepare(sql);try{s.bind(params);const result:Row[]=[];while(s.step())result.push(s.getAsObject());return result;}finally{s.free();}}
export function execute(db:Database,sql:string,params:SqlValue[]=[]):void{const s=db.prepare(sql);try{s.run(params);}finally{s.free();}}
export const hasTable=(db:Database,name:string):boolean=>query(db,"SELECT name FROM sqlite_master WHERE type='table' AND name=?",[name]).length===1;
export function accountFromRow(r:Row):CrmAccount{return{id:String(r.id),externalId:Number(r.external_id),domain:String(r.domain),name:String(r.name),currentUserId:Number(r.current_user_id),authorized:r.authorized===1,expiresAt:Number(r.expires_at),lastSyncAt:r.last_sync_at?String(r.last_sync_at):null,state:String(r.state) as SyncState,error:r.error?String(r.error):null,currency:r.currency?String(r.currency):null,authMode:r.auth_mode==='browser'?'browser':'oauth'};}
export function saveAccount(db:Database,a:CrmAccount):void{execute(db,'INSERT INTO crm_accounts(id,external_id,domain,name,current_user_id,authorized,expires_at,last_sync_at,state,error,currency,auth_mode) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,current_user_id=excluded.current_user_id,authorized=excluded.authorized,expires_at=excluded.expires_at,last_sync_at=excluded.last_sync_at,state=excluded.state,error=excluded.error,currency=excluded.currency,auth_mode=excluded.auth_mode',[a.id,a.externalId,a.domain,a.name,a.currentUserId,a.authorized?1:0,a.expiresAt,a.lastSyncAt,a.state,a.error,a.currency??null,a.authMode??'oauth']);}
export function crmSnapshot(db:Database,account:CrmAccount|null):CrmCache & ReturnType<typeof mapWorkspace>{
  const empty={account,contacts:[],companies:[],pipelines:[],notes:[],fields:[],clients:[],deals:[],tasks:[]};if(!account)return empty;
  const records=(kind:string)=>query(db,'SELECT payload_json,availability,last_seen_at FROM crm_entities WHERE account_id=? AND kind=? ORDER BY external_updated_at DESC',[account.id,kind]).map(r=>({...JSON.parse(String(r.payload_json)),cacheAvailability:r.availability,lastSeenAt:r.last_seen_at}) as CrmRecord);
  const editableNotes=hasTable(db,'crm_operations')?query(db,"SELECT entity_type,result_external_id FROM crm_operations WHERE account_id=? AND operation_type='note.create' AND status='confirmed' AND result_external_id IS NOT NULL",[account.id]).map(r=>`${r.entity_type}:${r.result_external_id}`):[];
  const fieldGroups=hasTable(db,'crm_field_groups')?query(db,'SELECT * FROM crm_field_groups WHERE account_id=? ORDER BY sort',[account.id]).map(r=>({entity:String(r.entity),id:String(r.group_id),name:String(r.name),sort:Number(r.sort)})):[];
  const talks=hasTable(db,'crm_talks')?query(db,'SELECT * FROM crm_talks WHERE account_id=? ORDER BY updated_at DESC',[account.id]).map(r=>({talkId:Number(r.talk_id),chatId:r.chat_id===null?null:String(r.chat_id),contactId:r.contact_id===null?null:Number(r.contact_id),entityId:r.entity_id===null?null:Number(r.entity_id),entityType:r.entity_type===null?null:String(r.entity_type),origin:r.origin===null?null:String(r.origin),sourceId:r.source_id===null?null:Number(r.source_id),status:r.status===null?null:String(r.status),isInWork:r.is_in_work===1,isRead:r.is_read===1,createdAt:r.created_at===null?null:Number(r.created_at),updatedAt:r.updated_at===null?null:Number(r.updated_at),availability:String(r.availability)})):[];
  const cache:CrmCache={account,talks,editableNotes,fieldGroups,taskTypes:records('task_type'),contactNotes:records('contact_note'),companyNotes:records('company_note'),contacts:records('contact'),companies:records('company'),pipelines:records('pipeline'),notes:records('note'),fields:query(db,'SELECT entity,payload_json FROM crm_fields WHERE account_id=?',[account.id]).map(r=>({entity:String(r.entity),definition:JSON.parse(String(r.payload_json)) as CrmRecord}))};
  const relations:CrmRelation[]=query(db,'SELECT * FROM crm_relations WHERE account_id=?',[account.id]).map(r=>({leadId:Number(r.lead_id),entityId:Number(r.entity_id),entityType:String(r.entity_type) as CrmRelation['entityType'],primary:r.is_primary===1}));
  const leads=records('lead').filter(l=>l.responsible_user_id===account.currentUserId);
  return {...cache,leads,relations,...mapWorkspace(account,leads,cache,relations,records('task'))};
}
export function commitSync(db:Database,b:SyncBatch,runId:string):void{
  const now=new Date().toISOString();db.run('BEGIN');
  try {
    const put=(kind:string,items:CrmRecord[])=>{execute(db,"UPDATE crm_entities SET availability='unavailable' WHERE account_id=? AND kind=?",[b.account.id,kind]);for(const item of items)execute(db,"INSERT INTO crm_entities VALUES(?,?,?,?,?,?,?,'active') ON CONFLICT(account_id,kind,external_id) DO UPDATE SET payload_json=excluded.payload_json,external_updated_at=excluded.external_updated_at,last_seen_at=excluded.last_seen_at,availability='active'",[b.account.id,kind,item.id,localId(b.account.id,kind,item.id),JSON.stringify(projectRecord(item)),typeof item.updated_at==='number'?item.updated_at:null,now]);};
    put('lead',b.leads);put('contact',b.contacts);put('company',b.companies);put('pipeline',b.pipelines);
    // Replace relations only for leads returned in this complete scope; missing leads retain their historical links.
    for(const lead of b.leads)execute(db,'DELETE FROM crm_relations WHERE account_id=? AND lead_id=?',[b.account.id,lead.id]);
    for(const r of b.relations)execute(db,'INSERT INTO crm_relations VALUES(?,?,?,?,?)',[b.account.id,r.leadId,r.entityType,r.entityId,r.primary?1:0]);
    if(b.tasks)put('task',b.tasks);if(b.notes)put('note',b.notes);if(b.contactNotes)put('contact_note',b.contactNotes);if(b.companyNotes)put('company_note',b.companyNotes);if(b.taskTypes)put('task_type',b.taskTypes);
    if(b.talks&&hasTable(db,'crm_talks')){execute(db,"UPDATE crm_talks SET availability='unavailable' WHERE account_id=?",[b.account.id]);for(const t of b.talks)execute(db,"INSERT INTO crm_talks VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'active') ON CONFLICT(account_id,talk_id) DO UPDATE SET chat_id=excluded.chat_id,contact_id=excluded.contact_id,entity_id=excluded.entity_id,entity_type=excluded.entity_type,origin=excluded.origin,source_id=excluded.source_id,status=excluded.status,is_in_work=excluded.is_in_work,is_read=excluded.is_read,created_at=excluded.created_at,updated_at=excluded.updated_at,last_seen_at=excluded.last_seen_at,availability='active'",[b.account.id,t.talkId,t.chatId,t.contactId,t.entityId,t.entityType,t.origin,t.sourceId,t.status,t.isInWork?1:0,t.isRead?1:0,t.createdAt,t.updatedAt,now]);}
    if(b.fieldGroups&&hasTable(db,'crm_field_groups')){execute(db,'DELETE FROM crm_field_groups WHERE account_id=?',[b.account.id]);for(const g of b.fieldGroups)execute(db,'INSERT OR REPLACE INTO crm_field_groups VALUES(?,?,?,?,?)',[b.account.id,g.entity,g.id,g.name,g.sort]);}
    if(b.fields){execute(db,'DELETE FROM crm_fields WHERE account_id=?',[b.account.id]);for(const f of b.fields)execute(db,'INSERT INTO crm_fields VALUES(?,?,?,?)',[b.account.id,f.entity,f.definition.id,JSON.stringify(projectRecord(f.definition))]);}
    saveAccount(db,{...b.account,lastSyncAt:now,state:b.warnings.length?'partial_error':'success',error:b.warnings.join('\n')||null});
    execute(db,'UPDATE sync_runs SET finished_at=?,state=?,warnings_json=?,counts_json=? WHERE id=?',[now,b.warnings.length?'partial_error':'success',JSON.stringify(b.warnings),JSON.stringify({leads:b.leads.length,contacts:b.contacts.length,companies:b.companies.length,tasks:b.tasks?.length??null}),runId]);db.run('COMMIT');
  }catch(error){db.run('ROLLBACK');throw error;}
}
export function beginSync(db:Database,accountId:string):string{const id=randomUUID();execute(db,'INSERT INTO sync_runs(id,account_id,started_at,state) VALUES(?,?,?,?)',[id,accountId,new Date().toISOString(),'running']);execute(db,"UPDATE crm_accounts SET state='running',error=NULL WHERE id=?",[accountId]);return id;}


const putOne=(db:Database,accountId:string,kind:string,item:CrmRecord,now:string)=>execute(db,"INSERT INTO crm_entities VALUES(?,?,?,?,?,?,?,'active') ON CONFLICT(account_id,kind,external_id) DO UPDATE SET payload_json=excluded.payload_json,external_updated_at=excluded.external_updated_at,last_seen_at=excluded.last_seen_at,availability='active'",[accountId,kind,item.id,localId(accountId,kind,item.id),JSON.stringify(projectRecord(item)),typeof item.updated_at==='number'?item.updated_at:null,now]);
/** Replaces one cached entity with the version amoCRM returned after a confirmed write. */
export function upsertEntity(db:Database,accountId:string,kind:string,item:CrmRecord):void{putOne(db,accountId,kind,item,new Date().toISOString());}
export interface ScopedBatch {leads:CrmRecord[];contacts:CrmRecord[];companies:CrmRecord[];tasks:CrmRecord[];notes:CrmRecord[];contactNotes:CrmRecord[];companyNotes:CrmRecord[];relations:CrmRelation[];talks?:CrmTalk[]}
/** Entity-level refresh for one workspace. Unlike a full sync it never marks unrelated records unavailable. */
export function upsertScoped(db:Database,accountId:string,b:ScopedBatch):void{
  const now=new Date().toISOString();db.run('BEGIN');
  try{
    for(const [kind,items] of [['lead',b.leads],['contact',b.contacts],['company',b.companies],['task',b.tasks],['note',b.notes],['contact_note',b.contactNotes],['company_note',b.companyNotes]] as const)for(const item of items)putOne(db,accountId,kind,item,now);
    if(b.talks&&hasTable(db,'crm_talks'))for(const t of b.talks)execute(db,"INSERT INTO crm_talks VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'active') ON CONFLICT(account_id,talk_id) DO UPDATE SET chat_id=excluded.chat_id,contact_id=excluded.contact_id,entity_id=excluded.entity_id,entity_type=excluded.entity_type,origin=excluded.origin,source_id=excluded.source_id,status=excluded.status,is_in_work=excluded.is_in_work,is_read=excluded.is_read,created_at=excluded.created_at,updated_at=excluded.updated_at,last_seen_at=excluded.last_seen_at,availability='active'",[accountId,t.talkId,t.chatId,t.contactId,t.entityId,t.entityType,t.origin,t.sourceId,t.status,t.isInWork?1:0,t.isRead?1:0,t.createdAt,t.updatedAt,now]);
    for(const lead of b.leads){execute(db,'DELETE FROM crm_relations WHERE account_id=? AND lead_id=?',[accountId,lead.id]);for(const r of b.relations.filter(x=>x.leadId===lead.id))execute(db,'INSERT INTO crm_relations VALUES(?,?,?,?,?)',[accountId,r.leadId,r.entityType,r.entityId,r.primary?1:0]);}
    db.run('COMMIT');
  }catch(error){db.run('ROLLBACK');throw error;}
}
