ALTER TABLE meetings ADD COLUMN source TEXT NOT NULL DEFAULT 'demo';
ALTER TABLE meetings ADD COLUMN account_id TEXT;
ALTER TABLE meetings ADD COLUMN integration_mode TEXT;
ALTER TABLE meetings ADD COLUMN external_meeting_id TEXT;
ALTER TABLE meetings ADD COLUMN external_recording_id TEXT;
ALTER TABLE meetings ADD COLUMN ended_at TEXT;
ALTER TABLE meetings ADD COLUMN organizer TEXT;
ALTER TABLE meetings ADD COLUMN source_created_at TEXT;
ALTER TABLE meetings ADD COLUMN source_updated_at TEXT;
ALTER TABLE meetings ADD COLUMN last_seen_at TEXT;
ALTER TABLE meetings ADD COLUMN synchronized_at TEXT;
ALTER TABLE meetings ADD COLUMN processing_status TEXT NOT NULL DEFAULT 'not_available';
CREATE INDEX idx_meetings_source_account ON meetings(source,account_id,started_at DESC);
CREATE TABLE kontur_accounts (id TEXT PRIMARY KEY,domain TEXT NOT NULL,mode TEXT NOT NULL CHECK(mode IN ('api','session')),external_user_id TEXT,display_name TEXT,state TEXT NOT NULL,last_sync_at TEXT,error TEXT);
CREATE TABLE meeting_source_ids (account_id TEXT NOT NULL,kind TEXT NOT NULL,external_id TEXT NOT NULL,meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,PRIMARY KEY(account_id,kind,external_id));
CREATE TABLE meeting_participants (id TEXT PRIMARY KEY,meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,recording_id TEXT NOT NULL,external_id TEXT,display_name TEXT NOT NULL,email TEXT,role TEXT,organizer INTEGER);
CREATE TABLE meeting_artifacts (meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,recording_id TEXT NOT NULL,type TEXT NOT NULL,state TEXT NOT NULL,external_id TEXT,version TEXT,generated_at TEXT,text TEXT,sections_json TEXT NOT NULL,source_url TEXT,PRIMARY KEY(meeting_id,recording_id,type));
CREATE TABLE transcript_segments (id TEXT PRIMARY KEY,meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,recording_id TEXT NOT NULL,sequence INTEGER NOT NULL,external_id TEXT,speaker_id TEXT,speaker_name TEXT NOT NULL,start_ms REAL,end_ms REAL,text TEXT NOT NULL,UNIQUE(meeting_id,recording_id,sequence));
CREATE INDEX idx_transcript_meeting_sequence ON transcript_segments(meeting_id,recording_id,sequence);
CREATE TABLE integration_sync_runs (id TEXT PRIMARY KEY,source TEXT NOT NULL,account_id TEXT NOT NULL,state TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT,meeting_count INTEGER NOT NULL DEFAULT 0,error TEXT);
