import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, CalendarDays, Check, Clock3, Mail, Phone, Plus, SlidersHorizontal, UserRound, BriefcaseBusiness, Info, CircleAlert } from 'lucide-react';
import { useApp } from '../App.tsx';
import {KonturConnection} from '../components/KonturConnection.tsx';
import {TalkMeeting} from '../components/TalkMeeting.tsx';
import {meetingCrmLabel} from '../domain/matching.ts';
import {artifactLabel} from '../domain/kontur.ts';
import { CrmConnection } from '../components/CrmConnection.tsx';
import { CrmDetails, noteText } from '../components/CrmDetails.tsx';
import type { Client, Deal, Meeting, Task } from '../domain/models.ts';
import { activeDeal, dayKey, formatDate, formatDuration, formatMoney } from '../domain/models.ts';
import { EmptyState, Modal, PageHeader, SearchField, Section, StageBadge, StatusBadge } from '../components/ui.tsx';

const todayKey = () => dayKey(new Date().toISOString());
const clientLabel = (client?: Client) => client?.companyName || client?.name || 'Не указан';
const dateSort = (a: Task, b: Task) => (a.dueAt || '9999').localeCompare(b.dueAt || '9999');
const latestMeeting = (meetings: Meeting[], clientId: string) => meetings.find(meeting => meeting.clientId === clientId);
const upcomingTask = (tasks: Task[], clientId: string) => tasks.filter(task => task.clientId === clientId && !task.completed).sort(dateSort)[0];
const dealForClient = (deals: Deal[], clientId: string) => deals.find(deal => deal.clientId === clientId && activeDeal(deal));
const back = (to: string, label: string) => <Link className="back-link" to={to}><ArrowLeft size={16}/>{label}</Link>;

export function Dashboard() {
  const { data } = useApp();
  const today = todayKey();
  const active = data.deals.filter(activeDeal);
  const meetingsToday = data.meetings.filter(meeting => dayKey(meeting.startedAt) === today).length;
  const overdue = data.tasks.filter(task => !task.completed && task.dueAt && task.dueAt < new Date().toISOString()).length;
  const attention = data.meetings.filter(meeting => meeting.matchingStatus !== 'linked'||meeting.crmLink?.status==='needs_review').length;
  const tasks = data.tasks.filter(task => !task.completed).sort(dateSort).slice(0, 5);
  return <><PageHeader title="Главная" subtitle="Всё важное по клиентам и сделкам — в одном месте"/>
    <div className="metric-grid">
      <Link to="/deals" className="metric"><span>Активные сделки</span><strong>{active.length}</strong><small>В работе сейчас <ArrowUpRight size={14}/></small></Link>
      <Link to="/meetings" className="metric"><span>Встречи сегодня</span><strong>{meetingsToday}</strong><small>По вашему календарю <ArrowUpRight size={14}/></small></Link>
      <Link to="/tasks" className="metric"><span>Просроченные задачи</span><strong>{overdue}</strong><small>Нужны действия <ArrowUpRight size={14}/></small></Link>
      <Link to="/meetings" className="metric"><span>Требуют внимания</span><strong>{attention}</strong><small>Встречи без точной привязки <ArrowUpRight size={14}/></small></Link>
    </div>
    <div className="dashboard-grid"><Section title="Ближайшие задачи" action={<Link className="text-link" to="/tasks">Все задачи <ArrowUpRight size={15}/></Link>}>
      {tasks.length ? <div className="stack">{tasks.map(task => <div className="simple-row" key={task.id}><span className="task-dot"/><div className="grow"><strong>{task.title}</strong><small>{clientLabel(data.clients.find(client => client.id === task.clientId))}</small></div><span className={`date-note${task.dueAt && task.dueAt < new Date().toISOString() ? ' overdue' : ''}`}>{formatDate(task.dueAt)}</span></div>)}</div> : <EmptyState title="Задач пока нет"/>}</Section>
      <Section title="Последние встречи" action={<Link className="text-link" to="/meetings">Все встречи <ArrowUpRight size={15}/></Link>}>
        {data.meetings.length ? <div className="stack">{data.meetings.slice(0, 4).map(meeting => <Link className="simple-row interactive" to={`/meetings/${meeting.id}`} key={meeting.id}><div className="list-icon"><CalendarDays size={17}/></div><div className="grow"><strong>{meeting.title}</strong><small>{clientLabel(data.clients.find(client => client.id === meeting.clientId))} · {meeting.source==='kontur_talk'&&!meeting.startedAt?'Время начала неизвестно':formatDate(meeting.startedAt)} · {formatDuration(meeting.durationSeconds)}</small></div>{meeting.source==='kontur_talk'?<span className="status status-neutral">{meeting.crmLink?.confirmed?'Привязана':meetingCrmLabel(meeting)}</span>:<StatusBadge status={meeting.matchingStatus}/>}</Link>)}</div> : <EmptyState title="Встреч пока нет"/>}</Section></div>
    <Section title="Сделки в работе" action={<Link className="text-link" to="/deals">Все сделки <ArrowUpRight size={15}/></Link>}><div className="deal-mini-grid">{active.slice(0, 4).map(deal => <Link className="deal-mini" to={`/clients/${deal.clientId}`} key={deal.id}><span className="eyebrow">{clientLabel(data.clients.find(client => client.id === deal.clientId))}</span><strong>{deal.title}</strong><div><StageBadge stage={deal.stageName}/><span>{formatMoney(deal.amount, deal.currency)}</span></div></Link>)}</div></Section>
  </>;
}

export function ClientsPage() {
  const { data } = useApp();
  const [search, setSearch] = useState('');
  const [sort, setSort] = useState<'name' | 'responsible'>('name');
  const clients = useMemo(() => data.clients.filter(client => `${client.companyName} ${client.name} ${client.responsibleName}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => (sort === 'name' ? clientLabel(a).localeCompare(clientLabel(b), 'ru') : (a.responsibleName || '').localeCompare(b.responsibleName || '', 'ru'))), [data.clients, search, sort]);
  return <><PageHeader title="Клиенты" subtitle={`${data.clients.length} клиентов в рабочем пространстве`}/><div className="toolbar"><SearchField value={search} onChange={setSearch} placeholder="Компания, контакт или менеджер"/><label className="select-wrap"><SlidersHorizontal size={16}/><select value={sort} onChange={event => setSort(event.target.value as 'name' | 'responsible')} aria-label="Сортировка клиентов"><option value="name">По названию</option><option value="responsible">По менеджеру</option></select></label></div>
    {clients.length ? <div className="table-card"><div className="table-head clients-grid"><span>КЛИЕНТ</span><span>ОТВЕТСТВЕННЫЙ</span><span>АКТИВНАЯ СДЕЛКА</span><span>ЭТАП</span><span>СЛЕДУЮЩАЯ ЗАДАЧА</span></div>{clients.map(client => { const deal = dealForClient(data.deals, client.id); const task = upcomingTask(data.tasks, client.id); return <Link className="table-row clients-grid" to={`/clients/${client.id}`} key={client.id}><div><strong>{clientLabel(client)}</strong><small>{client.name}</small><small>{[client.phone,client.email].filter(Boolean).join(' · ')||'Нет контактных данных'}</small></div><span>{client.responsibleName || '—'}</span><span>{deal?.title || '—'}</span><span>{deal ? <StageBadge stage={deal.stageName}/> : '—'}</span><span className="muted-cell">{task?.title || 'Нет задач'}</span></Link>; })}</div> : <EmptyState title="Клиенты не найдены" detail="Попробуйте изменить поисковый запрос"/>}</>;
}

export function ClientDetailsPage() {
  const { id } = useParams(); const { data } = useApp();
  const client = data.clients.find(item => item.id === id);
  if (!client) return <><PageHeader title="Клиент не найден"/>{back('/clients','К списку клиентов')}</>;
  const deals = data.deals.filter(deal => deal.clientId === id);
  const meetings = data.meetings.filter(meeting => meeting.clientId === id);
  const tasks = data.tasks.filter(task => task.clientId === id && !task.completed).sort(dateSort);
  const currentDeal = deals.find(activeDeal);
  const recent = latestMeeting(data.meetings, client.id);
  return <>{back('/clients','Клиенты')}<PageHeader title={clientLabel(client)} subtitle={`Контакт: ${client.name}`}/>
    <div className="client-summary"><div><span>ОТВЕТСТВЕННЫЙ</span><strong>{client.responsibleName || 'Не назначен'}</strong></div><div><span>АКТИВНАЯ СДЕЛКА</span><strong>{currentDeal?.title || 'Нет активной сделки'}</strong></div><div><span>ТЕКУЩИЙ ЭТАП</span>{currentDeal ? <StageBadge stage={currentDeal.stageName}/> : <strong>—</strong>}</div></div>
    <div className="detail-grid"><div className="detail-main">
      <Section title="О клиенте"><div className="info-list"><div><UserRound size={17}/><span>{client.name}</span></div><div><Phone size={17}/><span>{client.phone || 'Телефон не указан'}</span></div><div><Mail size={17}/><span>{client.email || 'Почта не указана'}</span></div><div><BriefcaseBusiness size={17}/><span>{client.companyName || 'Компания не указана'}</span></div></div></Section>
      <CrmDetails clientId={client.id}/><Section title="Сделки">{deals.length ? <div className="stack">{deals.map(deal => <div className="simple-row" key={deal.id}><div className="list-icon"><BriefcaseBusiness size={17}/></div><div className="grow"><strong>{deal.title}</strong><small>{formatMoney(deal.amount, deal.currency)}</small>{data.meetings.filter(m=>m.dealId===deal.id).map(m=><Link className="text-link" key={m.id} to={`/meetings/${m.id}`}>Встреча: {m.title}</Link>)}</div><StageBadge stage={deal.stageName}/></div>)}</div> : <EmptyState title="Сделок пока нет"/>}</Section>
      <Section title="Последняя встреча">{recent ? <div className="meeting-feature"><div className="feature-meta"><CalendarDays size={17}/>{formatDate(recent.startedAt)}<span>·</span><Clock3 size={17}/>{formatDuration(recent.durationSeconds)}</div><h3>{recent.title}</h3><p>{recent.sourceSummaryPreview??recent.summary}</p><Link className="button secondary" to={`/meetings/${recent.id}`}>Открыть встречу <ArrowUpRight size={16}/></Link></div> : <EmptyState title="Встреч пока нет"/>}</Section>
      <Section title="История встреч">{meetings.length ? <div className="stack">{meetings.map(meeting => <Link className="simple-row interactive" key={meeting.id} to={`/meetings/${meeting.id}`}><div className="list-icon"><CalendarDays size={17}/></div><div className="grow"><strong>{meeting.title}</strong><small>{meeting.source==='kontur_talk'&&!meeting.startedAt?'Время начала неизвестно':formatDate(meeting.startedAt)} · {formatDuration(meeting.durationSeconds)}</small></div>{meeting.source==='kontur_talk'?<span className="status status-neutral">{meeting.crmLink?.confirmed?'Привязана':meetingCrmLabel(meeting)}</span>:<StatusBadge status={meeting.matchingStatus}/>}</Link>)}</div> : <EmptyState title="Встреч пока нет"/>}</Section>
    </div><div className="detail-side"><Section title="Договорённости"><div className="agreement"><span className="agreement-icon"><Check size={17}/></span><p>{recent?.sourceSummaryPreview??recent?.summary??'Договорённости появятся после встречи.'}</p></div></Section><Section title="Ближайшие задачи">{tasks.length ? <div className="side-tasks">{tasks.map(task => <div key={task.id}><span className="task-dot"/><div><strong>{task.title}</strong><small>{formatDate(task.dueAt)}</small></div></div>)}</div> : <EmptyState title="Активных задач нет"/>}</Section><div className="future-card"><Plus size={20}/><strong>Переписка с клиентом</strong><p>История сообщений появится здесь после подключения канала связи.</p></div></div></div>
  </>;
}

export function DealsPage() {
  const { data } = useApp(); const [search, setSearch] = useState(''); const [stage, setStage] = useState('all'); const [owner, setOwner] = useState('all'); const [pipeline,setPipeline]=useState('all');
  const stages = [...new Set(data.deals.map(deal => deal.stageName))]; const owners = [...new Set(data.deals.map(deal => deal.responsibleName).filter((value): value is string => !!value))];
  const deals = data.deals.filter(deal => { const client = data.clients.find(item => item.id === deal.clientId); return (pipeline==='all'||deal.pipelineName===pipeline) && (stage === 'all' || deal.stageName === stage) && (owner === 'all' || deal.responsibleName === owner) && `${deal.title} ${clientLabel(client)}`.toLowerCase().includes(search.toLowerCase()); });
  return <><PageHeader title="Сделки" subtitle={`${data.deals.length} сделок · ${data.deals.filter(activeDeal).length} в работе`}/><div className="toolbar"><SearchField value={search} onChange={setSearch} placeholder="Найти сделку или клиента"/><label className="select-wrap"><select value={stage} onChange={event => setStage(event.target.value)} aria-label="Фильтр по этапу"><option value="all">Все этапы</option>{stages.map(value => <option key={value}>{value}</option>)}</select></label><label className="select-wrap"><select value={pipeline} onChange={e=>setPipeline(e.target.value)} aria-label="Фильтр по воронке"><option value="all">Все воронки</option>{[...new Set(data.deals.map(d=>d.pipelineName).filter((v):v is string=>!!v))].map(v=><option key={v}>{v}</option>)}</select></label>{data.settings.data_mode!=='amocrm'&&<label className="select-wrap"><select value={owner} onChange={event => setOwner(event.target.value)} aria-label="Фильтр по менеджеру"><option value="all">Все менеджеры</option>{owners.map(value => <option key={value}>{value}</option>)}</select></label>}</div>
    {deals.length ? <div className="table-card"><div className="table-head deals-grid"><span>СДЕЛКА</span><span>КЛИЕНТ</span><span>ЭТАП</span><span>ОТВЕТСТВЕННЫЙ</span><span>СУММА</span><span>{data.settings.data_mode==='amocrm'?'ПОСЛЕДНЕЕ ПРИМЕЧАНИЕ':'ПОСЛЕДНЯЯ ВСТРЕЧА'}</span><span>СЛЕДУЮЩАЯ ЗАДАЧА</span></div>{deals.map(deal => { const meeting = data.meetings.find(item => item.dealId === deal.id); const task = data.tasks.filter(item => item.dealId === deal.id && !item.completed).sort(dateSort)[0]; return <Link className="table-row deals-grid" to={`/clients/${deal.clientId}`} key={deal.id}><div><strong>{deal.title}</strong>{deal.availability==='unavailable'&&<small>Нет в последней синхронизации</small>}</div><span>{clientLabel(data.clients.find(client => client.id === deal.clientId))}</span><span><StageBadge stage={deal.stageName}/></span><span>{deal.responsibleName || '—'}</span><span>{formatMoney(deal.amount, deal.currency)}</span><span className="muted-cell">{data.settings.data_mode==='amocrm'?noteText(data.crm?.notes.find(n=>Number(n.entity_id)===Number(deal.externalId))):meeting ? formatDate(meeting.startedAt) : '—'}</span><span className="muted-cell">{task?.title || '—'}</span></Link>; })}</div> : <EmptyState title="Сделки не найдены" detail="Попробуйте изменить фильтры"/>}</>;
}

export function MeetingsPage() {
  const { data,busy,mutate } = useApp(); const [filter, setFilter] = useState('all');const [finding,setFinding]=useState(false),[result,setResult]=useState('');
  const options = [{key:'all',label:'Все'},{key:'linked',label:'Привязаны'},{key:'review',label:'Нужно проверить'},{key:'unlinked',label:'Не привязаны'}];
  const meetings = data.meetings.filter(meeting => filter==='all'||filter==='linked'&&meeting.matchingStatus==='linked'||filter==='review'&&(meeting.matchingStatus==='review'||meeting.crmLink?.status==='needs_review')||filter==='unlinked'&&meeting.matchingStatus==='unlinked');
  const findAll=async()=>{setFinding(true);setResult('');try{await mutate(async api=>{const next=await api.findMeetingClients();const items=next.meetings.filter(m=>!m.crmLink?.confirmed);const found=items.filter(m=>m.crmLink?.candidates.length).length;setResult(`${items.length} встречи обработаны · ${found} с предложениями · ${items.length-found} нужно выбрать вручную`);return next;});}finally{setFinding(false);}};
  return <><PageHeader title="Встречи" subtitle={data.kontur?`Встречи из Контур.Толка · ${data.kontur.meetingCount}`:"История разговоров с клиентами"} action={data.kontur&&<button className="button secondary" disabled={busy||data.settings.data_mode!=='amocrm'} onClick={()=>void findAll()}>{finding?'Ищем клиента в CRM...':'Найти клиентов для непривязанных встреч'}</button>}/>{result&&<p role="status">{result}</p>}<div className="segmented" role="group" aria-label="Фильтр встреч">{options.map(option => <button key={option.key} className={filter === option.key ? 'selected' : ''} onClick={() => setFilter(option.key)}>{option.label}</button>)}</div>
    {meetings.length ? <div className="meeting-list">{meetings.map(meeting => { const client = data.clients.find(item => item.id === meeting.clientId); const deal = data.deals.find(item => item.id === meeting.dealId); return <Link className="meeting-card" key={meeting.id} to={`/meetings/${meeting.id}`}><div className="meeting-date"><strong>{meeting.startedAt?new Date(meeting.startedAt).toLocaleDateString('ru-RU', { day: '2-digit' }):'—'}</strong><span>{meeting.startedAt?new Date(meeting.startedAt).toLocaleDateString('ru-RU', { month: 'short' }):'дата'}</span></div><div className="grow"><div className="meeting-title"><strong>{meeting.title}</strong>{meeting.source==='kontur_talk'?<span className="status status-neutral">{meeting.crmLink?.confirmed?'Привязана':meetingCrmLabel(meeting)}</span>:<StatusBadge status={meeting.matchingStatus}/>}</div><div className="meeting-meta"><span><Clock3 size={15}/>{meeting.source==='kontur_talk'&&!meeting.startedAt?'Время начала неизвестно':formatDate(meeting.startedAt)} · {formatDuration(meeting.durationSeconds)}</span><span><UserRound size={15}/>{meeting.participants.join(', ')}</span></div>{meeting.source==='kontur_talk'?<p>{meetingCrmLabel(meeting)} · Транскрипция: {artifactLabel(meeting.artifactStates?.transcript??'not_available')} · Протокол: {artifactLabel(meeting.artifactStates?.protocol??'not_available')}</p>:<p>{clientLabel(client)}{deal ? ` · ${deal.title}` : ''}</p>}</div><ArrowUpRight size={18}/></Link>; })}</div> : <EmptyState title="Встреч пока нет" detail={data.settings.data_mode==='amocrm'?'Встречи появятся после подключения Контур.Толк.':'Для этого фильтра ничего не найдено'}/>}</>;
}

export function MeetingDetailsPage() {
  const { id } = useParams(); const { data } = useApp(); const [tab, setTab] = useState<'summary' | 'transcript' | 'recording'>('summary');
  const meeting = data.meetings.find(item => item.id === id);
  if (!meeting) return <><PageHeader title="Встреча не найдена"/>{back('/meetings','К списку встреч')}</>;
  if(meeting.source==='kontur_talk')return <>{back('/meetings','Встречи')}<PageHeader title={meeting.title} subtitle={`${meeting.startedAt?formatDate(meeting.startedAt):'Время начала неизвестно'} · ${formatDuration(meeting.durationSeconds)}`}/><TalkMeeting meeting={meeting}/></>;
  const client = data.clients.find(item => item.id === meeting.clientId); const deal = data.deals.find(item => item.id === meeting.dealId);
  return <>{back('/meetings','Встречи')}<PageHeader title={meeting.title} subtitle={`${formatDate(meeting.startedAt)} · ${formatDuration(meeting.durationSeconds)}`} action={<button className="button disabled" disabled title="Появится в следующей версии">Подготовить заполнение CRM</button>}/>
    <div className="meeting-overview"><div><span>УЧАСТНИКИ</span><strong>{meeting.participants.join(', ')}</strong></div><div><span>КЛИЕНТ</span><strong>{client ? <Link to={`/clients/${client.id}`}>{clientLabel(client)}</Link> : 'Не указан'}</strong></div><div><span>СДЕЛКА</span><strong>{deal?.title || 'Не привязана'}</strong></div><div><span>СТАТУС</span><StatusBadge status={meeting.matchingStatus}/></div></div>
    <div className="detail-tabs" role="tablist" aria-label="Содержание встречи"><button role="tab" aria-selected={tab === 'summary'} className={tab === 'summary' ? 'active' : ''} onClick={() => setTab('summary')}>Резюме</button><button role="tab" aria-selected={tab === 'transcript'} className={tab === 'transcript' ? 'active' : ''} onClick={() => setTab('transcript')}>Транскрипция</button><button role="tab" aria-selected={tab === 'recording'} className={tab === 'recording' ? 'active' : ''} onClick={() => setTab('recording')}>Запись</button></div>
    <div className="tab-panel">{tab === 'summary' && <><h2>Краткое резюме</h2><p className="long-copy">{meeting.summary || 'Резюме пока нет.'}</p><div className="notice"><Info size={17}/>Демонстрационные данные встречи. Анализ появится после подключения сервиса.</div></>}{tab === 'transcript' && <><h2>Транскрипция</h2>{meeting.transcript.length ? <div className="transcript">{meeting.transcript.map((line,index) => <div className="transcript-line" key={`${line.time}-${index}`}><div><time>{line.time}</time><strong>{line.speaker}</strong></div><p>{line.text}</p></div>)}</div> : <EmptyState title="Транскрипции пока нет"/>}</>}{tab === 'recording' && <><h2>Запись встречи</h2><div className="recording-placeholder"><div className="recording-play">▶</div><strong>Запись появится после подключения Контур.Толк</strong><span>В этой версии воспроизведение недоступно</span></div></>}</div>
  </>;
}

export function TasksPage() {
  const { data, mutate, busy } = useApp();
  const now = new Date().toISOString(); const today = todayKey();
  const groups = [
    { title: 'Просроченные', tasks: data.tasks.filter(task => !task.completed && task.dueAt && task.dueAt < now && dayKey(task.dueAt) !== today) },
    { title: 'Сегодня', tasks: data.tasks.filter(task => !task.completed && task.dueAt && dayKey(task.dueAt) === today) },
    { title: 'Предстоящие', tasks: data.tasks.filter(task => !task.completed && (!task.dueAt || task.dueAt > now) && (!task.dueAt || dayKey(task.dueAt) !== today)) },
    { title: 'Выполненные', tasks: data.tasks.filter(task => task.completed) }
  ];
  return <><PageHeader title="Задачи" subtitle={data.settings.data_mode==='amocrm'?'Задачи amoCRM — только чтение. Изменяйте их в CRM.':'Следующие шаги по клиентам и сделкам'}/>{groups.map(group => <Section key={group.title} title={`${group.title} · ${group.tasks.length}`}><div className="task-list">{group.tasks.length ? group.tasks.sort(dateSort).map(task => { const client = data.clients.find(item => item.id === task.clientId); const deal = data.deals.find(item => item.id === task.dealId); return <div className={`task-row${task.completed ? ' done' : ''}`} key={task.id}><label className="check-control"><input type="checkbox" aria-label={`Статус задачи: ${task.title}`} title={task.source==='amocrm'?'Изменяется в amoCRM':undefined} checked={task.completed} disabled={busy||task.source==='amocrm'} onChange={event => void mutate(api => api.setTaskCompleted(task.id, event.target.checked))}/><span/></label><div className="grow"><strong>{task.title}</strong><small>{clientLabel(client)}{deal ? ` · ${deal.title}` : ''}</small></div><span className={`date-note${group.title === 'Просроченные' ? ' overdue' : ''}`}>{formatDate(task.dueAt)}</span>{client && <Link className="icon-button" to={`/clients/${client.id}`} aria-label={`Открыть ${clientLabel(client)}`}><ArrowUpRight size={17}/></Link>}</div>; }) : <EmptyState title={group.title === 'Выполненные' ? 'Выполненных задач пока нет' : 'Задач нет'}/>}</div></Section>)}</>;
}

export function TemplatesPage() {
  const { data } = useApp(); const [selected, setSelected] = useState(data.templates[0]?.id);
  const template = data.templates.find(item => item.id === selected);
  return <><PageHeader title="Шаблоны" subtitle="Структура заполнения CRM после встречи"/><div className="templates-layout"><div className="template-list">{data.templates.map(item => <button key={item.id} className={`template-choice${item.id === selected ? ' selected' : ''}`} onClick={() => setSelected(item.id)}><div className="template-icon"><FileIcon/></div><div><strong>{item.title}</strong><small>{item.description}</small></div><ArrowUpRight size={17}/></button>)}</div><div className="template-detail">{template ? <><div className="template-detail-head"><span className="eyebrow">ШАБЛОН ВСТРЕЧИ</span><h2>{template.title}</h2><p>{template.description}</p></div><div className="field-list">{template.fields.map((field,index) => <div key={field.key}><span>{String(index + 1).padStart(2,'0')}</span><strong>{field.title}</strong></div>)}</div><div className="notice"><Info size={17}/>Редактирование шаблонов появится в следующей версии.</div></> : <EmptyState title="Шаблон не найден"/>}</div></div></>;
}
function FileIcon() { return <span className="file-icon">▤</span>; }

export function SettingsPage() {
  const { data, mutate, busy } = useApp();
  const [name, setName] = useState(data.profile.displayName);
  const [modal, setModal] = useState<'amoCRM' | 'Контур.Толк' | 'reset' | null>(null);
  return <><PageHeader title="Настройки" subtitle="Профиль, подключения и данные приложения"/><div className="settings-columns"><div className="settings-main">
    <Section title="Профиль"><form className="profile-form" onSubmit={event => { event.preventDefault(); void mutate(api => api.updateProfile(name)); }}><label>Отображаемое имя<input value={name} maxLength={100} onChange={event => setName(event.target.value)} required/></label><button className="button primary" disabled={busy || name.trim() === data.profile.displayName}>Сохранить</button></form></Section>
    <Section title="Интеграции"><CrmConnection/><KonturConnection/><div className="integration-list">{data.integrations.filter(i=>i.type!=='amoCRM'&&i.type!=='Контур.Толк').map(integration => <div className="integration-row" key={integration.id}><div className="integration-logo">{integration.type === 'AI' ? '✦' : integration.type[0]}</div><div className="grow"><strong>{integration.type}</strong><small>{integration.status}</small></div>{integration.type !== 'AI' && <button className="button secondary" onClick={() => setModal(integration.type as 'amoCRM' | 'Контур.Толк')}>Подключить</button>}</div>)}</div></Section>
    </div><div className="settings-side"><Section title="Приложение"><div className="setting-line"><span>Версия</span><strong>{data.version}</strong></div><div className="setting-line"><span>Демо-режим</span><strong>{data.settings.data_mode==='amocrm'||data.kontur?'Выключен':'Включён'}</strong></div><div className="setting-block"><span>Локальная база данных</span><code>{data.databaseLocation}</code></div><div className="setting-line"><span>Уведомления</span><label className="switch"><input type="checkbox" checked={data.settings.notifications === 'on'} disabled={busy} onChange={event => void mutate(api => api.setSetting('notifications', event.target.checked ? 'on' : 'off'))}/><span/></label></div><button className="reset-button" onClick={() => setModal('reset')}>Сбросить демо-данные</button></Section><div className="notice settings-notice"><CircleAlert size={17}/>AI-функции появятся в следующей версии.</div></div></div>
    {modal && <Modal title={modal === 'reset' ? 'Сбросить демо-данные?' : `Подключение ${modal}`} onClose={() => setModal(null)}>{modal === 'reset' ? <><p>Демонстрационные клиенты, сделки, встречи и задачи восстановятся в исходном виде. Профиль, настройки и кэш amoCRM сохранятся.</p><div className="modal-actions"><button className="button secondary" onClick={() => setModal(null)}>Отмена</button><button className="button danger" disabled={busy} onClick={() => { void mutate(api => api.resetDemo()); setModal(null);  }}>Сбросить данные</button></div></> : <><p>Авторизация и синхронизация с {modal} будут доступны в следующей версии. Сейчас приложение работает с локальными демонстрационными данными.</p><div className="modal-actions"><button className="button primary" onClick={() => setModal(null)}>Понятно</button></div></>}</Modal>}
  </>;
}
