import { useState } from 'react';
import { useApp } from '../App.tsx';
import type { ConnectInput } from '../domain/crm.ts';
import { formatDate } from '../domain/models.ts';
import { Modal } from './ui.tsx';
const initial:ConnectInput={domain:'',clientId:'',clientSecret:'',redirectUri:'',code:''};
const labels:Record<keyof ConnectInput,string>={domain:'Домен аккаунта',clientId:'ID интеграции',clientSecret:'Секретный ключ',redirectUri:'Redirect URI',code:'Код авторизации'};
const stateLabel:Record<string,string>={idle:'Готово к синхронизации',running:'Синхронизация',success:'Обновлено',partial_error:'Обновлено частично',failed:'Ошибка синхронизации'};
export function CrmConnection(){
  const {data,busy,crmAction,mutate,progress}=useApp();const account=data.crm?.account;
  const [modal,setModal]=useState<'connect'|'disconnect'|null>(null);const [step,setStep]=useState(1);const [input,setInput]=useState<ConnectInput>(initial);const [purge,setPurge]=useState(false);const [result,setResult]=useState('');
  const [mode,setMode]=useState<'browser'|'oauth'>('browser');const [browserOpened,setBrowserOpened]=useState(false);
  const open=()=>{setInput({...initial,domain:account?.domain??''});setStep(1);setMode('browser');setBrowserOpened(false);setResult('');setModal('connect');};
  const openBrowser=async()=>{const response=await crmAction?.(api=>api.openCrmBrowser(input.domain));if(response){setResult(response.message);setBrowserOpened(response.ok);}};
  const verifyBrowser=async()=>{const response=await crmAction?.(async api=>{const connected=await api.verifyCrmBrowser();return connected.ok?api.syncCrm():connected;});if(response){setResult(response.message);if(response.ok)setModal(null);}};
  const submit=async()=>{if(!crmAction)return;const payload={...input};setInput({...input,clientSecret:'',code:''});setResult('');const response=await crmAction(async api=>{const connected=await api.connectCrm(payload);payload.code='';payload.clientSecret='';return connected.ok?api.syncCrm():connected;});setResult(response.message);if(response.ok)setModal(null);};
  return <div className="crm-connection"><div className="integration-row"><div className="integration-logo">a</div><div className="grow"><strong>amoCRM</strong><small>{account?`${account.domain} · ${account.authorized?'Подключено':'Кэш без подключения'}`:'Не подключено'}</small></div><button className="button secondary" disabled={busy} onClick={open}>{account?'Подключить заново':'Подключить'}</button></div>
    {account&&<div className="crm-metadata"><div className="setting-line"><span>Подключение</span><strong>{account.authMode==='browser'?'Локальная браузерная сессия':'OAuth-интеграция'}</strong></div><div className="setting-line"><span>Текущий пользователь</span><strong>#{account.currentUserId}</strong></div><div className="setting-line"><span>Последнее обновление</span><strong>{account.lastSyncAt?formatDate(account.lastSyncAt):'Ещё не было'}</strong></div><div className="setting-line"><span>Статус</span><strong>{stateLabel[account.state]}</strong></div>{account.error&&<p className="crm-warning">{account.error}</p>}<div className="crm-counts">{data.crm?.leads?.length??0} сделок · {data.crm?.contacts.length??0} контактов · {data.crm?.companies.length??0} компаний · {data.crm?.pipelines.length??0} воронок · {data.crm?.fields.length??0} полей</div><div className="connection-actions"><button className="button primary" disabled={busy||!account.authorized} onClick={()=>void crmAction?.(api=>api.syncCrm())}>Синхронизировать</button><button className="button secondary" disabled={busy} onClick={()=>{setPurge(false);setModal('disconnect');}}>Отключить</button></div></div>}
    <div className="setting-line"><span>Источник рабочего пространства</span><select aria-label="Источник данных" value={data.settings.data_mode??'demo'} disabled={busy} onChange={e=>void mutate(api=>api.setSetting('data_mode',e.target.value))}><option value="demo">Демо</option><option value="amocrm" disabled={!account}>amoCRM — сохранённый кэш</option></select></div>
    <p className="muted-copy">Из amoCRM загружаются только данные для чтения. Задачи меняются в самой CRM. </p>
    {modal==='connect'&&<Modal title={mode==='browser'?'Вход сотрудника в amoCRM':step===1?'Подключение amoCRM':'Ключи интеграции'} onClose={()=>{if(!busy){setInput(initial);setModal(null);}}}>
      <div className="connection-methods" role="group" aria-label="Способ подключения"><button className={`button ${mode==='browser'?'primary':'secondary'}`} disabled={busy} aria-pressed={mode==='browser'} onClick={()=>{setMode('browser');setResult('');}}>Вход через браузер</button><button className={`button ${mode==='oauth'?'primary':'secondary'}`} disabled={busy} aria-pressed={mode==='oauth'} onClick={()=>{setMode('oauth');setResult('');}}>Через интеграцию</button></div>
      {mode==='browser'?<><p>Войдите в свой аккаунт на официальном сайте amoCRM в отдельном окне. Пароль и код подтверждения вводятся только на сайте.</p><form className="crm-form" onSubmit={e=>{e.preventDefault();void openBrowser();}}><label>Домен аккаунта<input required value={input.domain} placeholder="company.amocrm.ru" autoComplete="off" spellCheck={false} disabled={busy} onChange={e=>{setInput({...input,domain:e.target.value});setBrowserOpened(false);}}/></label><button className="button secondary" disabled={busy}>Открыть окно входа</button></form><p className="muted-copy">После входа вернитесь сюда. Проверим, разрешает ли ваша сессия чтение данных. При успешной проверке сессия сохранится на этом компьютере с шифрованием Windows.</p><p className="muted-copy">Этот способ пока проверяется. Если сайт не разрешает чтение через сессию, потребуется отдельный адаптер интерфейса.</p>{result&&<p role="status">{result}</p>}{busy&&<p role="status">{progress?.stage??'Проверяем подключение…'}</p>}<div className="modal-actions"><button className="button primary" disabled={busy||!browserOpened} onClick={()=>void verifyBrowser()}>Проверить доступ и загрузить</button></div></>:step===1?<><p>Создайте приватную интеграцию в amoМаркет вашего аккаунта. Для создания интеграции нужны права администратора. Приложение определит пользователя, чьи права получил токен.</p><ol className="wizard-steps"><li>Откройте интеграцию и вкладку «Ключи и доступы».</li><li>Скопируйте ID интеграции, секретный ключ и Redirect URI.</li><li>Получите новый код авторизации: он действует 20 минут.</li></ol><p>Ключи хранятся на этом компьютере с шифрованием Windows. Пароль от amoCRM не требуется.</p><div className="modal-actions"><button className="button primary" onClick={()=>setStep(2)}>Ввести данные</button></div></>:<form className="crm-form" onSubmit={e=>{e.preventDefault();void submit();}} autoComplete="off">{(Object.keys(labels) as (keyof ConnectInput)[]).map(key=><label key={key}>{labels[key]}<input required value={input[key]} type={key==='clientSecret'||key==='code'?'password':'text'} placeholder={key==='domain'?'company.amocrm.ru':key==='redirectUri'?'Точно как в интеграции':''} autoComplete="off" spellCheck={false} disabled={busy} onChange={e=>setInput({...input,[key]:e.target.value})}/></label>)}{busy&&<p role="status">{progress?.stage??'Подключаем аккаунт…'}</p>}{result&&<p role="alert">{result}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setStep(1)}>Назад</button><button className="button primary" disabled={busy}>Подключить и загрузить</button></div></form>}
    </Modal>}
    {modal==='disconnect'&&<Modal title="Отключить amoCRM?" onClose={()=>{if(!busy)setModal(null);}}><p>Ключи подключения будут удалены с этого компьютера. Сохранённые данные можно оставить для просмотра.</p><label className="purge-choice"><input type="checkbox" checked={purge} disabled={busy} onChange={e=>setPurge(e.target.checked)}/> Также удалить локальный кэш этого аккаунта</label><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Отмена</button><button className="button danger" disabled={busy} onClick={async()=>{const response=await crmAction?.(api=>api.disconnectCrm(purge));if(response?.ok)setModal(null);}}>Отключить{purge?' и удалить кэш':''}</button></div></Modal>}
  </div>;
}
