import { useState } from 'react';
import { ExternalLink, KeyRound, LogIn, RefreshCw, ShieldCheck, Unplug } from 'lucide-react';
import { useApp } from '../App.tsx';
import type { ConnectInput } from '../domain/crm.ts';
import { formatDate } from '../domain/models.ts';
import { Badge, Modal, Notice, Select, type Tone } from './ui.tsx';
const initial:ConnectInput={domain:'',clientId:'',clientSecret:'',redirectUri:'',code:''};
const labels:Record<keyof ConnectInput,string>={domain:'Домен аккаунта',clientId:'ID интеграции',clientSecret:'Секретный ключ',redirectUri:'Redirect URI',code:'Код авторизации'};
const stateLabel:Record<string,string>={idle:'Готово к синхронизации',running:'Синхронизация',success:'Обновлено',partial_error:'Обновлено частично',failed:'Ошибка синхронизации'};
const stateTone:Record<string,Tone>={idle:'neutral',running:'info',success:'success',partial_error:'warning',failed:'danger'};
export function CrmConnection(){
  const {data,busy,crmAction,mutate,progress}=useApp();const account=data.crm?.account;
  const [modal,setModal]=useState<'connect'|'disconnect'|null>(null);const [step,setStep]=useState(1);const [input,setInput]=useState<ConnectInput>(initial);const [purge,setPurge]=useState(false);const [result,setResult]=useState('');const [resultOk,setResultOk]=useState(false);
  const [mode,setMode]=useState<'browser'|'oauth'>('browser');const [browserOpened,setBrowserOpened]=useState(false);
  const open=()=>{setInput({...initial,domain:account?.domain??''});setStep(1);setMode('browser');setBrowserOpened(false);setResult('');setModal('connect');};
  const openBrowser=async()=>{const response=await crmAction?.(api=>api.openCrmBrowser(input.domain));if(response){setResult(response.message);setResultOk(response.ok);setBrowserOpened(response.ok);}};
  const verifyBrowser=async()=>{const response=await crmAction?.(async api=>{const connected=await api.verifyCrmBrowser();return connected.ok?api.syncCrm():connected;});if(response){setResult(response.message);setResultOk(response.ok);if(response.ok)setModal(null);}};
  const submit=async()=>{if(!crmAction)return;const payload={...input};setInput({...input,clientSecret:'',code:''});setResult('');const response=await crmAction(async api=>{const connected=await api.connectCrm(payload);payload.code='';payload.clientSecret='';return connected.ok?api.syncCrm():connected;});setResult(response.message);if(response.ok)setModal(null);};
  const counts=account?[[data.crm?.leads?.length??0,'сделок'],[data.crm?.contacts.length??0,'контактов'],[data.crm?.companies.length??0,'компаний'],[data.crm?.pipelines.length??0,'воронок'],[data.crm?.fields.length??0,'полей']] as const:[];
  return <div className={`integration-card${account?.authorized?' connected':''}`}>
    <div className="integration-head"><span className="integration-logo amo">amo</span><div className="grow"><strong>amoCRM</strong><small>{account?`${account.domain} · ${account.authorized?'Подключено':'Кэш без подключения'}`:'Не подключено'}</small></div>{account&&<Badge tone={account.authorized?stateTone[account.state]:'warning'} dot>{account.authorized?stateLabel[account.state]:'Только кэш'}</Badge>}<button className={`btn ${account?'':'btn-primary'}`} disabled={busy} onClick={open}>{account?'Подключить заново':'Подключить'}</button></div>
    {account&&<div className="integration-body"><div className="integration-facts"><div><span className="eyebrow">Подключение</span><strong>{account.authMode==='browser'?'Браузерная сессия':'OAuth-интеграция'}</strong></div><div><span className="eyebrow">Пользователь</span><strong className="mono">#{account.currentUserId}</strong></div><div><span className="eyebrow">Обновлено</span><strong>{account.lastSyncAt?formatDate(account.lastSyncAt):'Ещё не было'}</strong></div></div>
      {account.error&&<Notice tone="warning">{account.error}</Notice>}
      <div className="count-chips">{counts.map(([n,label])=><span key={label}><strong>{n}</strong> {label}</span>)}</div>
      <div className="integration-actions"><button className="btn btn-primary" disabled={busy||!account.authorized} onClick={()=>void crmAction?.(api=>api.syncCrm())}><RefreshCw size={15}/>Синхронизировать</button><button className="btn btn-ghost" disabled={busy} onClick={()=>{setPurge(false);setModal('disconnect');}}><Unplug size={15}/>Отключить</button></div></div>}
    <div className="integration-foot"><span>Источник рабочего пространства</span><Select disabled={busy} label="Источник данных" value={data.settings.data_mode??'demo'} onChange={value=>void mutate(api=>api.setSetting('data_mode',value))}><option value="demo">Демо</option><option value="amocrm" disabled={!account}>amoCRM — сохранённый кэш</option></Select></div>
    <p className="integration-copy">Из amoCRM загружаются только данные для чтения. Задачи меняются в самой CRM.</p>
    {modal==='connect'&&<Modal icon={mode==='browser'?LogIn:KeyRound} title={mode==='browser'?'Вход сотрудника в amoCRM':step===1?'Подключение amoCRM':'Ключи интеграции'} onClose={()=>{if(!busy){setInput(initial);setModal(null);}}}>
      <div className="method-switch" role="group" aria-label="Способ подключения"><button className={mode==='browser'?'selected':''} disabled={busy} aria-pressed={mode==='browser'} onClick={()=>{setMode('browser');setResult('');}}>Вход через браузер</button><button className={mode==='oauth'?'selected':''} disabled={busy} aria-pressed={mode==='oauth'} onClick={()=>{setMode('oauth');setResult('');}}>Через интеграцию</button></div>
      {mode==='browser'?<>
        <ol className="steps"><li className={browserOpened?'done':'current'}><span className="step-num">1</span><div><strong>Откройте окно входа</strong><p>Войдите в свой аккаунт на официальном сайте amoCRM. Пароль и код подтверждения вводятся только на сайте.</p><form className="inline-form" onSubmit={e=>{e.preventDefault();void openBrowser();}}><label className="field">Домен аккаунта<input required value={input.domain} placeholder="company.amocrm.ru" autoComplete="off" spellCheck={false} disabled={busy} onChange={e=>{setInput({...input,domain:e.target.value});setBrowserOpened(false);}}/></label><button className="btn" disabled={busy}><ExternalLink size={15}/>Открыть окно входа</button></form></div></li>
          <li className={browserOpened?'current':''}><span className="step-num">2</span><div><strong>Проверьте доступ</strong><p>После входа вернитесь сюда. Проверим, разрешает ли сессия чтение данных, и сохраним её на этом компьютере с шифрованием Windows.</p></div></li></ol>
        {result&&<Notice tone={resultOk?'info':'danger'} role="status">{result}</Notice>}{busy&&<p role="status" className="busy-line"><span className="spinner"/>{progress?.stage??'Проверяем подключение…'}</p>}
        <p className="muted small-copy">Этот способ пока проверяется. Если сайт не разрешает чтение через сессию, потребуется отдельный адаптер интерфейса.</p>
        <div className="modal-actions"><button className="btn btn-primary" disabled={busy||!browserOpened} onClick={()=>void verifyBrowser()}><ShieldCheck size={16}/>Проверить доступ и загрузить</button></div></>
      :step===1?<><p>Создайте приватную интеграцию в amoМаркет вашего аккаунта. Для этого нужны права администратора. Приложение определит пользователя, чьи права получил токен.</p><ol className="steps compact"><li><span className="step-num">1</span><div>Откройте интеграцию и вкладку «Ключи и доступы».</div></li><li><span className="step-num">2</span><div>Скопируйте ID интеграции, секретный ключ и Redirect URI.</div></li><li><span className="step-num">3</span><div>Получите новый код авторизации — он действует 20 минут.</div></li></ol><Notice icon={ShieldCheck}>Ключи хранятся на этом компьютере с шифрованием Windows. Пароль от amoCRM не требуется.</Notice><div className="modal-actions"><button className="btn btn-primary" onClick={()=>setStep(2)}>Ввести данные</button></div></>
      :<form className="form-grid" onSubmit={e=>{e.preventDefault();void submit();}} autoComplete="off">{(Object.keys(labels) as (keyof ConnectInput)[]).map(key=><label className="field" key={key}>{labels[key]}<input required value={input[key]} type={key==='clientSecret'||key==='code'?'password':'text'} placeholder={key==='domain'?'company.amocrm.ru':key==='redirectUri'?'Точно как в интеграции':''} autoComplete="off" spellCheck={false} disabled={busy} onChange={e=>setInput({...input,[key]:e.target.value})}/></label>)}{busy&&<p role="status" className="busy-line"><span className="spinner"/>{progress?.stage??'Подключаем аккаунт…'}</p>}{result&&<Notice tone="danger" role="alert">{result}</Notice>}<div className="modal-actions split"><button type="button" className="btn btn-ghost" disabled={busy} onClick={()=>setStep(1)}>Назад</button><button className="btn btn-primary" disabled={busy}>Подключить и загрузить</button></div></form>}
    </Modal>}
    {modal==='disconnect'&&<Modal icon={Unplug} title="Отключить amoCRM?" onClose={()=>{if(!busy)setModal(null);}}><p>Ключи подключения будут удалены с этого компьютера. Сохранённые данные можно оставить для просмотра.</p><label className="checkbox"><input type="checkbox" checked={purge} disabled={busy} onChange={e=>setPurge(e.target.checked)}/> Также удалить локальный кэш этого аккаунта</label><div className="modal-actions"><button className="btn" disabled={busy} onClick={()=>setModal(null)}>Отмена</button><button className="btn btn-danger" disabled={busy} onClick={async()=>{const response=await crmAction?.(api=>api.disconnectCrm(purge));if(response?.ok)setModal(null);}}>Отключить{purge?' и удалить кэш':''}</button></div></Modal>}
  </div>;
}
