import { Building2, ChevronDown, NotebookText, SlidersHorizontal, UsersRound } from 'lucide-react';
import { useApp } from '../App.tsx';
import type { CrmRecord } from '../domain/crm.ts';
import { formatDate } from '../domain/models.ts';
import { Avatar, Badge, Section, EmptyState } from './ui.tsx';
export const noteText=(note:CrmRecord|undefined):string=>{const p=note?.params;if(p&&typeof p==='object'&&'text'in p&&typeof p.text==='string')return p.text;return typeof note?.text==='string'?note.text:note?`Примечание: ${String(note.note_type??'событие')}`:'—';};
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const kindLabel:Record<string,string>={leads:'Сделка',contacts:'Контакт',companies:'Компания'};
export function CrmDetails({clientId}:{clientId:string}){
  const {data}=useApp();const crm=data.crm;if(data.settings.data_mode!=='amocrm'||!crm)return null;
  const dealIds=new Set(data.deals.filter(d=>d.clientId===clientId).map(d=>Number(d.externalId)));
  const relations=crm.relations?.filter(r=>dealIds.has(r.leadId))??[];
  const contacts=crm.contacts.filter(c=>relations.some(r=>r.entityType==='contacts'&&r.entityId===c.id));const companies=crm.companies.filter(c=>relations.some(r=>r.entityType==='companies'&&r.entityId===c.id));const leads=crm.leads?.filter(l=>dealIds.has(l.id))??[];
  const notes=crm.notes.filter(n=>dealIds.has(Number(n.entity_id))).sort((a,b)=>Number(b.created_at??0)-Number(a.created_at??0));
  const entities=[...leads.map(value=>({kind:'leads',value})),...contacts.map(value=>({kind:'contacts',value})),...companies.map(value=>({kind:'companies',value}))];
  return <><Section title="Связанные контакты и компании" icon={UsersRound} flush>{contacts.length||companies.length?<div className="list">{[...companies,...contacts].map(entity=>{const company=companies.includes(entity);return <div className="list-row" key={`${company?'company':'contact'}:${entity.id}`}>{company?<span className="list-icon info"><Building2 size={17}/></span>:<Avatar name={entity.name??'#'} round/>}<div className="grow"><span className="title">{entity.name??`#${entity.id}`}</span><span className="meta">{company?'Компания':'Контакт'} · <span className="mono">amoCRM #{entity.id}</span></span></div>{entity.cacheAvailability==='unavailable'&&<Badge tone="warning" small>Нет в последней синхронизации</Badge>}</div>;})}</div>:<EmptyState compact title="Контакты и компании не привязаны"/>}</Section>
    <Section title="Примечания amoCRM" icon={NotebookText}>{notes.length?<div className="notes">{notes.slice(0,20).map(n=><div className="note" key={n.id}><div className="note-head"><span className="mono">{formatDate(typeof n.created_at==='number'?new Date(n.created_at*1000).toISOString():null)}</span><span className="muted">Сделка #{String(n.entity_id)}</span></div><p>{noteText(n)}</p></div>)}{notes.length>20&&<small className="muted">Показаны последние 20 из {notes.length} сохранённых примечаний.</small>}</div>:<EmptyState compact title="Примечаний пока нет"/>}</Section>
    <Section title="Пользовательские поля amoCRM" icon={SlidersHorizontal}><div className="field-groups">{entities.map(({kind,value},index)=>{const fields=Array.isArray(value.custom_fields_values)?value.custom_fields_values:[];return <details className="field-group" key={`${kind}:${value.id}`} open={index===0}><summary><Badge tone="neutral" small>{kindLabel[kind]}</Badge><strong>{value.name??`#${value.id}`}</strong><span className="count" aria-hidden="true"><span>{fields.length}</span></span><ChevronDown size={16} className="chevron"/></summary>{fields.length?<div className="field-values">{fields.map((raw,i)=>{const field=object(raw);const definition=crm.fields.find(f=>f.entity===kind&&f.definition.id===field.field_id)?.definition;const values=Array.isArray(field.values)?field.values.map(entry=>{const v=object(entry).value;return typeof v==='object'?JSON.stringify(v):String(v??'—');}).join(', '):'—';return <div className="kv" key={i}><span>{String(field.field_name??definition?.name??field.field_code??`Поле #${field.field_id}`)}</span><strong>{values}</strong></div>;})}</div>:<p className="muted">Нет заполненных полей</p>}</details>;})}</div></Section></>;
}
