import {useState} from 'react';
import {useApp} from '../App.tsx';
import {Modal} from './ui.tsx';
import {formatDate} from '../domain/models.ts';
export function KonturConnection(){
  const {data,busy,crmAction}=useApp();const account=data.kontur;const [modal,setModal]=useState<'connect'|'disconnect'|null>(null);const [mode,setMode]=useState<'session'|'api'>('session');const [domain,setDomain]=useState(account?.domain??'');const [secret,setSecret]=useState('');const [opened,setOpened]=useState(false);const [message,setMessage]=useState('');
  const labels={connected:'Подключено',disconnected:'Не подключено',needs_login:'Войдите снова',syncing:'Обновление встреч',failed:'Не удалось обновить'};
  const connect=async()=>{const apiKey=secret;setSecret('');const result=await crmAction?.(api=>api.connectKontur({mode,domain,...(mode==='api'?{apiKey}:{})}));setMessage(result?.message??'');if(result?.ok){const sync=await crmAction?.(api=>api.syncKontur());setMessage(sync?.message??'');if(sync?.ok)setModal(null);}};
  return <><div className="integration-row"><div className="integration-logo">К</div><div className="grow"><strong>Контур.Толк</strong><small>{account?labels[account.state]:'Не подключено'}</small>{account&&<><small>{account.displayName??account.domain} · {account.domain}</small><small>Встреч: {account.meetingCount} · Обновлено: {account.lastSyncAt?formatDate(account.lastSyncAt):'ещё не загружались'}</small>{account.error&&<small role="status">{account.error}</small>}</>}</div></div>
    <div className="kontur-actions">{account&&account.state!=='disconnected'?<><button className="button secondary" disabled={busy} onClick={()=>void crmAction?.(api=>api.syncKontur())}>Обновить встречи</button><button className="text-link" disabled={busy} onClick={()=>{setMode(account.mode);setDomain(account.domain);setOpened(false);setMessage('');setModal('connect');}}>Войти снова</button><button className="text-link" disabled={busy} onClick={()=>setModal('disconnect')}>Отключить</button></>:<button className="button secondary" disabled={busy} onClick={()=>{setMessage('');setModal('connect');}}>Подключить</button>}</div>
    {modal==='connect'&&<Modal title="Подключение Контур.Толка" onClose={()=>{if(!busy){setSecret('');setModal(null);}}}><div className="segmented"><button className={mode==='session'?'selected':''} disabled={busy} onClick={()=>{setMode('session');setSecret('');}}>Обычный вход</button><button className={mode==='api'?'selected':''} disabled={busy} onClick={()=>setMode('api')}>Через API</button></div><p>{mode==='session'?'Войдите в официальном окне Толка обычным способом, в том числе через Яндекс. После входа проверьте подключение.':'Укажите ключ API, выданный администратором вашего пространства.'}</p><form className="connection-form" onSubmit={event=>{event.preventDefault();if(mode==='api'){void connect();return;}void (async()=>{const r=await crmAction?.(api=>api.openKontur(domain));setMessage(r?.message??'');if(r?.ok)setOpened(true);})();}}><label>Адрес пространства Толка<input autoComplete="off" placeholder="company.ktalk.ru" value={domain} onChange={e=>{setDomain(e.target.value);setOpened(false);}} required disabled={busy}/></label>{mode==='api'&&<label>Ключ API<input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} required disabled={busy}/></label>}<div className="modal-actions"><button className="button primary" disabled={busy}>{mode==='session'?'Открыть окно Толка':'Подключить и загрузить встречи'}</button></div></form>{mode==='session'&&<button className="button secondary" disabled={busy||!opened} onClick={()=>void connect()}>Проверить подключение и загрузить</button>}{message&&<p role="status">{message}</p>}<p className="muted-cell">Данные и сессия хранятся на этом компьютере. Пароли и коды вводите только на странице Контура.</p></Modal>}
    {modal==='disconnect'&&<Modal title="Отключить Контур.Толк?" onClose={()=>!busy&&setModal(null)}><p>Обычное отключение сохранит встречи для просмотра. Можно также удалить их локальные данные.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Отмена</button><button className="button secondary" disabled={busy} onClick={()=>void (async()=>{const r=await crmAction?.(api=>api.disconnectKontur(false));if(r?.ok)setModal(null);})()}>Отключить</button><button className="button danger" disabled={busy} onClick={()=>void (async()=>{const r=await crmAction?.(api=>api.disconnectKontur(true));if(r?.ok)setModal(null);})()}>Отключить и удалить локальные данные</button></div></Modal>}
  </>;
}
