import {useState} from 'react';
import {ExternalLink, KeyRound, LogIn, RefreshCw, ShieldCheck, Unplug} from 'lucide-react';
import {useApp} from '../App.tsx';
import {Badge, Modal, Notice, Segmented, type Tone} from './ui.tsx';
import {formatDate} from '../domain/models.ts';
const labels={connected:'Подключено',disconnected:'Не подключено',needs_login:'Войдите снова',syncing:'Обновление встреч',failed:'Не удалось обновить'};
const tones:Record<keyof typeof labels,Tone>={connected:'success',disconnected:'neutral',needs_login:'warning',syncing:'info',failed:'danger'};
export function KonturConnection(){
  const {data,busy,crmAction}=useApp();const account=data.kontur;const [modal,setModal]=useState<'connect'|'disconnect'|null>(null);const [mode,setMode]=useState<'session'|'api'>('session');const [domain,setDomain]=useState(account?.domain??'');const [secret,setSecret]=useState('');const [opened,setOpened]=useState(false);const [message,setMessage]=useState('');
  const connect=async()=>{const apiKey=secret;setSecret('');const result=await crmAction?.(api=>api.connectKontur({mode,domain,...(mode==='api'?{apiKey}:{})}));setMessage(result?.message??'');if(result?.ok){const sync=await crmAction?.(api=>api.syncKontur());setMessage(sync?.message??'');if(sync?.ok)setModal(null);}};
  const active=account&&account.state!=='disconnected';
  return <div className={`integration-card${account?.state==='connected'?' connected':''}`}>
    <div className="integration-head"><span className="integration-logo kontur">К</span><div className="grow"><strong>Контур.Толк</strong><small>{account?`${account.displayName??account.domain} · ${account.domain}`:'Не подключено'}</small></div>{account&&<Badge tone={tones[account.state]} dot>{labels[account.state]}</Badge>}{!active&&<button className="btn btn-primary" disabled={busy} onClick={()=>{setMessage('');setModal('connect');}}>Подключить</button>}</div>
    {account&&<div className="integration-body"><div className="integration-facts"><div><span className="eyebrow">Встреч</span><strong className="mono">{account.meetingCount}</strong></div><div><span className="eyebrow">Режим</span><strong>{account.mode==='api'?'API-ключ':'Вход сотрудника'}</strong></div><div><span className="eyebrow">Обновлено</span><strong>{account.lastSyncAt?formatDate(account.lastSyncAt):'Ещё не загружались'}</strong></div></div>
      {account.error&&<Notice tone="warning" role="status">{account.error}</Notice>}
      {active&&<div className="integration-actions"><button className="btn btn-primary" disabled={busy} onClick={()=>void crmAction?.(api=>api.syncKontur())}><RefreshCw size={15}/>Обновить встречи</button><button className="btn btn-ghost" disabled={busy} onClick={()=>{setMode(account.mode);setDomain(account.domain);setOpened(false);setMessage('');setModal('connect');}}><LogIn size={15}/>Войти снова</button><button className="btn btn-ghost" disabled={busy} onClick={()=>setModal('disconnect')}><Unplug size={15}/>Отключить</button></div>}</div>}
    <p className="integration-copy">Записи, транскрипции и пересказы встреч. Видео не скачивается — запись открывается в Толке.</p>
    {modal==='connect'&&<Modal icon={mode==='session'?LogIn:KeyRound} title="Подключение Контур.Толка" onClose={()=>{if(!busy){setSecret('');setModal(null);}}}>
      <Segmented label="Способ подключения" value={mode} onChange={value=>{setMode(value);setSecret('');}} options={[{key:'session',label:'Обычный вход'},{key:'api',label:'Через API'}]}/>
      <p>{mode==='session'?'Войдите в официальном окне Толка обычным способом, в том числе через Яндекс. После входа проверьте подключение.':'Укажите ключ API, выданный администратором вашего пространства.'}</p>
      <form className="form-grid" onSubmit={event=>{event.preventDefault();if(mode==='api'){void connect();return;}void (async()=>{const r=await crmAction?.(api=>api.openKontur(domain));setMessage(r?.message??'');if(r?.ok)setOpened(true);})();}}><label className="field">Адрес пространства Толка<input autoComplete="off" placeholder="company.ktalk.ru" value={domain} onChange={e=>{setDomain(e.target.value);setOpened(false);}} required disabled={busy}/></label>{mode==='api'&&<label className="field">Ключ API<input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} required disabled={busy}/></label>}<div className="modal-actions split">{mode==='session'?<><button className="btn" disabled={busy}><ExternalLink size={15}/>Открыть окно Толка</button><button type="button" className="btn btn-primary" disabled={busy||!opened} onClick={()=>void connect()}><ShieldCheck size={16}/>Проверить подключение и загрузить</button></>:<button className="btn btn-primary" disabled={busy}>Подключить и загрузить встречи</button>}</div></form>
      {message&&<Notice tone="info" role="status">{message}</Notice>}<p className="muted small-copy">Данные и сессия хранятся на этом компьютере. Пароли и коды вводите только на странице Контура.</p></Modal>}
    {modal==='disconnect'&&<Modal icon={Unplug} title="Отключить Контур.Толк?" onClose={()=>!busy&&setModal(null)}><p>Обычное отключение сохранит встречи для просмотра. Можно также удалить их локальные данные.</p><div className="modal-actions split"><button className="btn btn-danger-soft" disabled={busy} onClick={()=>void (async()=>{const r=await crmAction?.(api=>api.disconnectKontur(true));if(r?.ok)setModal(null);})()}>Отключить и удалить данные</button><span className="row"><button className="btn" disabled={busy} onClick={()=>setModal(null)}>Отмена</button><button className="btn btn-primary" disabled={busy} onClick={()=>void (async()=>{const r=await crmAction?.(api=>api.disconnectKontur(false));if(r?.ok)setModal(null);})()}>Отключить</button></span></div></Modal>}
  </div>;
}
