import {useEffect,useState} from 'react';
import type {Meeting} from '../domain/models.ts';
import {formatDate,formatDuration} from '../domain/models.ts';
import {artifactLabel,formatTimestamp,type MeetingArtifacts,type TranscriptPage,type ArtifactType} from '../domain/kontur.ts';
import {getBrowserDemoApi} from '../services/browserDemo.ts';
import {sourceRetellingText} from '../domain/sourceText.ts';
import {MeetingCrmMatch} from './MeetingCrmMatch.tsx';
import {meetingCrmLabel} from '../domain/matching.ts';
import {EmptyState,Section} from './ui.tsx';
const names:Record<ArtifactType,string>={recording:'Запись',transcript:'Транскрипция',summary:'Пересказ',protocol:'Протокол'};
export function TalkMeeting({meeting}:{meeting:Meeting}){
  const api=window.talkcrm??getBrowserDemoApi();const [tab,setTab]=useState<'overview'|ArtifactType>('overview');const [materials,setMaterials]=useState<MeetingArtifacts|null>(null);const [page,setPage]=useState<TranscriptPage|null>(null);const [search,setSearch]=useState('');const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [highlight,setHighlight]=useState<string|null>(null);
  useEffect(()=>{if(highlight&&page&&!loading)document.getElementById('segment-'+highlight)?.scrollIntoView?.({block:'center'});},[highlight,page,loading]);
  const navigateEvidence=async(segmentId:string)=>{try{const at=await api.getTranscriptLocation(meeting.id,segmentId);setSearch('');setOffset(Math.floor(at/100)*100);setHighlight(segmentId);setTab('transcript');}catch{setError('Фрагмент обновился. Найдите упоминание по поиску в транскрипции.');}};
  useEffect(()=>{let active=true;api.getMeetingArtifacts(meeting.id).then(v=>{if(active)setMaterials(v);}).catch(()=>{if(active)setError('Не удалось прочитать сохранённые материалы.');});return()=>{active=false;};},[api,meeting.id,meeting.synchronizedAt]);
  useEffect(()=>{if(tab!=='transcript')return;let active=true;setLoading(true);const timer=setTimeout(()=>{void api.getTranscriptPage(meeting.id,offset,100,search).then(v=>{if(active){setPage(v);setError('');}}).catch(()=>{if(active)setError('Не удалось прочитать транскрипцию.');}).finally(()=>{if(active)setLoading(false);});},200);return()=>{active=false;clearTimeout(timer);};},[api,meeting.id,meeting.synchronizedAt,offset,search,tab]);
  return <><MeetingCrmMatch meeting={meeting} onEvidence={id=>void navigateEvidence(id)}/><div className="detail-tabs talk-tabs" role="tablist" aria-label="Содержание встречи">{(['overview','transcript','summary','protocol','recording'] as const).map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='overview'?'Обзор':names[t]}</button>)}</div><div className="tab-panel" role="tabpanel">{error&&<p role="alert">{error}</p>}{tab==='overview'&&<><div className="meeting-overview"><div><span>ДАТА ВСТРЕЧИ</span><strong>{meeting.startedAt?formatDate(meeting.startedAt):'Время начала неизвестно'}</strong></div><div><span>ДЛИТЕЛЬНОСТЬ</span><strong>{formatDuration(meeting.durationSeconds)}</strong></div><div><span>ИСТОЧНИК</span><strong>Контур.Толк</strong></div><div><span>СВЯЗЬ С КЛИЕНТОМ</span><strong>{meeting.crmLink?.confirmed?'Подтверждена':meetingCrmLabel(meeting)}</strong></div></div><p className="muted-cell">Запись создана в Толке: {formatDate(meeting.sourceCreatedAt??null)} · Данные обновлены: {formatDate(meeting.synchronizedAt??null)}</p>{meeting.organizer&&<p>Организатор: {meeting.organizer}</p>}<h2>Материалы встречи</h2><div className="artifact-grid">{Object.entries(names).map(([type,label])=><div key={type}><strong>{label}</strong><span>{artifactLabel(meeting.artifactStates?.[type as ArtifactType]??'not_available')}</span></div>)}</div><h2>Участники</h2><div className="stack">{materials?.participants.map((p,i)=><div className="simple-row" key={p.externalId??i}><div><strong>{p.displayName}</strong><small>{[p.email,p.role,p.organizer===true?'Организатор':null].filter(Boolean).join(' · ')}</small></div></div>)}</div>{!materials&&<p role="status">Загружаем материалы…</p>}</>}
    {tab==='transcript'&&<><h2>Транскрипция</h2><input className="transcript-search" type="search" aria-label="Поиск по транскрипции" placeholder="Найти в разговоре" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/>{loading?<p role="status">Загружаем фрагменты…</p>:page?.segments.length?<><p className="muted-cell">{offset+1}–{offset+page.segments.length} из {page.total}{search?' совпадений':''}</p><div className="transcript">{page.segments.map(s=><div className={`transcript-line${highlight===s.id?' evidence-highlight':''}`} id={'segment-'+s.id} key={s.id}><div><time>{formatTimestamp(s.startMs)}{s.endMs!==null?`–${formatTimestamp(s.endMs)}`:''}</time><strong>{s.speakerName}</strong></div><p>{s.text}</p></div>)}</div><div className="kontur-actions"><button className="button secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Предыдущие</button><button className="button secondary" disabled={offset+100>=page.total} onClick={()=>setOffset(offset+100)}>Следующие</button></div></>:<EmptyState title={search?'Совпадений нет':`Транскрипция: ${artifactLabel(meeting.artifactStates?.transcript??'not_available').toLowerCase()}`}/>}</>}
    {(tab==='summary'||tab==='protocol')&&<>{materials?.artifacts.filter(a=>a.type===tab).map(a=><Section title={materials.artifacts.filter(x=>x.type===tab).length>1?`${names[tab]} · запись ${materials.artifacts.filter(x=>x.type===tab).indexOf(a)+1}`:names[tab]} key={a.recordingId}><p className="muted-cell">{artifactLabel(a.state)}</p>{a.sections.length?a.sections.map((s,i)=><div className="source-section" key={i}>{s.timestampMs!==null&&<time>{formatTimestamp(s.timestampMs)}</time>}<p className="long-copy">{sourceRetellingText(s.text)}</p></div>):a.text?<p className="long-copy">{sourceRetellingText(a.text)}</p>:<p>В Толке пока нет доступного {tab==='summary'?'пересказа':'протокола'}.</p>}</Section>)}<p className="muted-cell">Материалы предоставлены Контур.Толком.</p></>}
    {tab==='recording'&&<><h2>Записи встречи</h2>{materials?.artifacts.filter(a=>a.type==='recording').map((a,i)=><div className="simple-row" key={a.recordingId}><div className="grow"><strong>Запись {i+1}</strong><small>{artifactLabel(a.state)}</small></div><button className="button secondary" disabled={!a.sourceUrl} onClick={()=>void api.openTalkRecording(meeting.id,a.recordingId).then(r=>{if(!r.ok)setError(r.message);}).catch(()=>setError('Не удалось открыть запись.'))}>Открыть в Толке</button></div>)}<p className="muted-cell">Для просмотра запись открывается в Контур.Толке.</p></>}
  </div></>;
}
