import {Fragment,useEffect,useState,type ReactNode} from 'react';
import {ChevronLeft,ChevronRight,ExternalLink,FileAudio,FileText,MessageSquareText,ScrollText,Search,Sparkles,Users} from 'lucide-react';
import type {Meeting} from '../domain/models.ts';
import {formatDate,formatDuration} from '../domain/models.ts';
import {artifactLabel,formatTimestamp,type ArtifactState,type MeetingArtifacts,type TranscriptPage,type ArtifactType} from '../domain/kontur.ts';
import {getBrowserDemoApi} from '../services/browserDemo.ts';
import {sourceRetellingText} from '../domain/sourceText.ts';
import {MeetingCrmMatch} from './MeetingCrmMatch.tsx';
import {Avatar,Badge,EmptyState,Facts,Notice,Section,type Tone} from './ui.tsx';
const names:Record<ArtifactType,string>={recording:'Запись',transcript:'Транскрипция',summary:'Пересказ',protocol:'Протокол'};
const icons={recording:FileAudio,transcript:MessageSquareText,summary:Sparkles,protocol:ScrollText};
const stateTone:Record<ArtifactState,Tone>={ready:'success',processing:'warning',failed:'danger',not_available:'neutral'};
const fold=(s:string)=>s.toLocaleLowerCase('ru-RU').replace(/ё/g,'е');
function highlight(text:string,query:string):ReactNode{const q=fold(query.trim());if(!q)return text;const parts:ReactNode[]=[];const lower=fold(text);let at=0;for(let i=lower.indexOf(q);i>=0;i=lower.indexOf(q,at)){parts.push(text.slice(at,i),<mark key={i}>{text.slice(i,i+q.length)}</mark>);at=i+q.length;}parts.push(text.slice(at));return parts.map((p,i)=><Fragment key={i}>{p}</Fragment>);}
export function TalkMeeting({meeting}:{meeting:Meeting}){
  const api=window.talkcrm??getBrowserDemoApi();const [tab,setTab]=useState<'overview'|ArtifactType>('overview');const [materials,setMaterials]=useState<MeetingArtifacts|null>(null);const [page,setPage]=useState<TranscriptPage|null>(null);const [search,setSearch]=useState('');const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [mark,setMark]=useState<string|null>(null);
  useEffect(()=>{if(mark&&page&&!loading)document.getElementById('segment-'+mark)?.scrollIntoView?.({block:'center',behavior:'smooth'});},[mark,page,loading]);
  const navigateEvidence=async(segmentId:string)=>{try{const at=await api.getTranscriptLocation(meeting.id,segmentId);setSearch('');setOffset(Math.floor(at/100)*100);setMark(segmentId);setTab('transcript');}catch{setError('Фрагмент обновился. Найдите упоминание по поиску в транскрипции.');}};
  useEffect(()=>{let active=true;api.getMeetingArtifacts(meeting.id).then(v=>{if(active)setMaterials(v);}).catch(()=>{if(active)setError('Не удалось прочитать сохранённые материалы.');});return()=>{active=false;};},[api,meeting.id,meeting.synchronizedAt]);
  useEffect(()=>{if(tab!=='transcript')return;let active=true;setLoading(true);const timer=setTimeout(()=>{void api.getTranscriptPage(meeting.id,offset,100,search).then(v=>{if(active){setPage(v);setError('');}}).catch(()=>{if(active)setError('Не удалось прочитать транскрипцию.');}).finally(()=>{if(active)setLoading(false);});},200);return()=>{active=false;clearTimeout(timer);};},[api,meeting.id,meeting.synchronizedAt,offset,search,tab]);
  const states=meeting.artifactStates??{};
  const pager=page&&page.total>100&&<div className="pager"><button className="btn btn-sm" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}><ChevronLeft size={15}/>Предыдущие</button><span className="mono muted">{offset+1}–{offset+(page?.segments.length??0)} из {page.total}</span><button className="btn btn-sm" disabled={offset+100>=page.total} onClick={()=>setOffset(offset+100)}>Следующие<ChevronRight size={15}/></button></div>;
  return <div className="meeting-layout"><div className="meeting-content">
    <div className="tabs" role="tablist" aria-label="Содержание встречи">{(['overview','transcript','summary','protocol','recording'] as const).map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='overview'?'Обзор':names[t]}{t!=='overview'&&<span aria-hidden="true" className={`tab-state ${states[t]??'not_available'}`}/>}</button>)}</div>
    <div className="panel tab-panel" role="tabpanel">{error&&<Notice tone="danger" role="alert">{error}</Notice>}
    {tab==='overview'&&<div className="overview">
      <Facts items={[{label:'Дата встречи',value:meeting.startedAt?formatDate(meeting.startedAt):'Время начала неизвестно'},{label:'Длительность',value:formatDuration(meeting.durationSeconds)},{label:'Источник',value:'Контур.Толк'}]}/>
      <p className="muted source-dates">Запись создана в Толке: {formatDate(meeting.sourceCreatedAt??null)} · Данные обновлены: {formatDate(meeting.synchronizedAt??null)}{meeting.organizer?` · Организатор: ${meeting.organizer}`:''}</p>
      <h3 className="subhead">Материалы встречи</h3>
      <div className="artifact-grid">{(Object.keys(names) as ArtifactType[]).map(type=>{const Icon=icons[type];const state=states[type]??'not_available';return <button key={type} className={`artifact-tile ${state}`} onClick={()=>setTab(type)}><span className="artifact-icon"><Icon size={18}/></span><strong>{names[type]}</strong><Badge tone={stateTone[state]} dot small>{artifactLabel(state)}</Badge></button>;})}</div>
      {meeting.sourceSummaryPreview&&<><h3 className="subhead">Кратко из пересказа</h3><blockquote className="retelling-preview">{sourceRetellingText(meeting.sourceSummaryPreview)}</blockquote></>}
    </div>}
    {tab==='transcript'&&<><div className="transcript-tools"><label className="search grow"><Search size={17}/><input type="search" aria-label="Поиск по транскрипции" placeholder="Найти в разговоре" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/></label>{page&&!loading&&<span className="muted transcript-count">{page.total} {search?'совпадений':'реплик'}</span>}</div>
      {loading?<div className="transcript-loading" role="status"><span className="spinner"/>Загружаем фрагменты…</div>:page?.segments.length?<>{pager}<div className="transcript">{page.segments.map(s=><div className={`transcript-line${mark===s.id?' evidence-highlight':''}`} id={'segment-'+s.id} key={s.id}><Avatar name={s.speakerName} size="sm" round/><div className="grow"><div className="line-head"><strong>{s.speakerName}</strong><time>{formatTimestamp(s.startMs)}{s.endMs!==null?`–${formatTimestamp(s.endMs)}`:''}</time></div><p>{highlight(s.text,search)}</p></div></div>)}</div>{pager}</>:<EmptyState icon={search?Search:MessageSquareText} title={search?'Совпадений нет':`Транскрипция: ${artifactLabel(states.transcript??'not_available').toLowerCase()}`}/>}</>}
    {(tab==='summary'||tab==='protocol')&&<div className="artifact-text">{materials?.artifacts.filter(a=>a.type===tab).map(a=>{const list=materials.artifacts.filter(x=>x.type===tab);return <article className="source-artifact" key={a.recordingId}><div className="source-artifact-head"><h3>{list.length>1?`${names[tab]} · запись ${list.indexOf(a)+1}`:names[tab]}</h3><Badge tone={stateTone[a.state]} dot small>{artifactLabel(a.state)}</Badge></div>{a.sections.length?a.sections.map((s,i)=><div className="source-section" key={i}>{s.timestampMs!==null&&<time>{formatTimestamp(s.timestampMs)}</time>}<p className="long-copy">{sourceRetellingText(s.text)}</p></div>):a.text?<p className="long-copy">{sourceRetellingText(a.text)}</p>:<p className="muted">В Толке пока нет доступного {tab==='summary'?'пересказа':'протокола'}.</p>}</article>;})}{materials&&!materials.artifacts.some(a=>a.type===tab)&&<EmptyState icon={FileText} title={`${names[tab]} недоступен`}/>}<p className="muted small-copy">Материалы предоставлены Контур.Толком и показаны без изменений.</p></div>}
    {tab==='recording'&&<div className="list recordings">{materials?.artifacts.filter(a=>a.type==='recording').map((a,i)=><div className="list-row" key={a.recordingId}><span className="list-icon accent"><FileAudio size={18}/></span><div className="grow"><span className="title">Запись {i+1}</span><span className="meta">{artifactLabel(a.state)}</span></div><button className="btn" disabled={!a.sourceUrl} onClick={()=>void api.openTalkRecording(meeting.id,a.recordingId).then(r=>{if(!r.ok)setError(r.message);}).catch(()=>setError('Не удалось открыть запись.'))}><ExternalLink size={15}/>Открыть в Толке</button></div>)}<p className="muted small-copy">Для просмотра запись открывается в Контур.Толке.</p></div>}
    </div>
  </div><aside className="meeting-side">
    <MeetingCrmMatch meeting={meeting} onEvidence={id=>void navigateEvidence(id)}/>
    <Section title="Участники" icon={Users} flush>{materials?materials.participants.length?<div className="list">{materials.participants.map((p,i)=><div className="list-row" key={p.externalId??i}><Avatar name={p.displayName} size="sm" round/><div className="grow"><span className="title">{p.displayName}</span>{(p.email||p.role)&&<span className="meta">{[p.email,p.role].filter(Boolean).join(' · ')}</span>}</div>{p.organizer===true&&<Badge tone="accent" small>Организатор</Badge>}</div>)}</div>:<EmptyState compact title="Участники не указаны"/>:<p role="status" className="busy-line pad"><span className="spinner"/>Загружаем материалы…</p>}</Section>
  </aside></div>;
}
