import fs from 'node:fs';
import path from 'node:path';
import initSqlJs from 'sql.js';
const directory=path.join(process.env.APPDATA!,'TalkCRM Desktop');const SQL=await initSqlJs();const before=new SQL.Database(new Uint8Array(fs.readFileSync(path.join(directory,'backups/phase4-20261004/talkcrm-before-0.4.0.sqlite'))));const after=new SQL.Database(new Uint8Array(fs.readFileSync(path.join(directory,'talkcrm.sqlite'))));
const rows=(db:InstanceType<typeof SQL.Database>,sql:string)=>db.exec(sql)[0]?.values??[];
const stableMeetingIds=JSON.stringify(rows(before,"SELECT id FROM meetings WHERE source='kontur_talk' ORDER BY id"))===JSON.stringify(rows(after,"SELECT id FROM meetings WHERE source='kontur_talk' ORDER BY id"));
const stableSegmentIds=JSON.stringify(rows(before,'SELECT id FROM transcript_segments ORDER BY id'))===JSON.stringify(rows(after,'SELECT id FROM transcript_segments ORDER BY id'));
const report={version:'0.4.0',stableMeetingIds,stableSegmentIds,realConfirmed:Number(rows(after,'SELECT COUNT(*) FROM meeting_crm_links WHERE confirmed_json IS NOT NULL')[0][0]),crm:{state:rows(after,'SELECT state FROM crm_accounts')[0][0],leads:Number(rows(after,"SELECT COUNT(*) FROM crm_entities WHERE kind='lead' AND availability='active'")[0][0]),contacts:Number(rows(after,"SELECT COUNT(*) FROM crm_entities WHERE kind='contact' AND availability='active'")[0][0]),fields:Number(rows(after,'SELECT COUNT(*) FROM crm_fields')[0][0])},kontur:{state:rows(after,'SELECT state FROM kontur_accounts')[0][0],meetings:Number(rows(after,"SELECT COUNT(*) FROM meetings WHERE source='kontur_talk'")[0][0]),recordings:Number(rows(after,"SELECT COUNT(*) FROM meeting_artifacts WHERE type='recording'")[0][0]),segments:Number(rows(after,'SELECT COUNT(*) FROM transcript_segments')[0][0]),retellings:Number(rows(after,"SELECT COUNT(*) FROM meeting_artifacts WHERE type='summary' AND state='ready'")[0][0]),successfulRuns:Number(rows(after,"SELECT COUNT(*) FROM integration_sync_runs WHERE state='complete'")[0][0])}};
before.close();after.close();if(!stableMeetingIds||!stableSegmentIds||report.realConfirmed!==0||report.crm.state!=='success'||report.kontur.state!=='connected')throw new Error('Regression check failed');fs.writeFileSync('docs/validation/matching-regression.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
